### PR TITLE
Win32 findfile fixes: Add support for Git for Windows 2 and other git.exe installations

### PR DESCRIPTION
**Pull request by ethomson**
Resurrecting #5150

### CODE REVIEW

**Comment by csware** [comment]
So, any news with this PR?

**Comment by csware** [comment]
@ethomson What do we do with this PR? Is there is anything needed, I cannot change anything.

**Comment by csware** [comment]
All people relying on the autotection won't get the right config file ATM.

Btw. Git dropped the applkication config layer, should we drop it on libgit2 as well (or at least the auto-detection for it)?

**Comment by ethomson** [comment]
Fixed in #6151 - thanks again @csware

**Pull request closed without merging**
