### PR TITLE
Test with MinGW on AppVeyor for maint/v0.22 branch

### PR DESCRIPTION
**Pull request by tkelman**
backporting most of #2946 to maint/v0.22

### CODE REVIEW

**Comment by tkelman** [comment]
The OSX Travis failure in https://travis-ci.org/libgit2/libgit2/jobs/63716785 looks like a spurious timeout, would anyone mind restarting it?

**Comment by nulltoken** [comment]
@tkelman Done!

**Comment by nulltoken** [comment]
@tkelman Done!

**Comment by nulltoken** [comment]
@tkelman Done!

**Comment by tkelman** [comment]
Thanks much, looks better now. I'm not really familiar enough with the MSVC build to know what that 64 bit failure is about, but it may have something to do with the `-D STDCALL=ON` build option which isn't being used on master? Is there some cmakery on master to decide when or when not to set that option? If so, should that be backported?

**Comment by tkelman** [comment]
Aha, it looks like maybe the commits from #2832 should be backported to work around that test failure?

**Pull request closed without merging**
