### PR TITLE
Release v0.26.4

### PR DESCRIPTION
**Pull request by pks-t**
Backport of v0.27.1 to maint/0.26. This is mainly intended as a help for objective-git, which is currently stalled due to libssh2 linking issues, but it might be useful to others, as well.

### CODE REVIEW

**Comment by pks-t** [comment]
Backported #4588 and #4584 to fix Bitbucket-specific tests

**Comment by ethomson** [comment]
Your last two commit messages reference 0.27 still (though they correctly update the version number in the product).  Otherwise I'm 👍

**Comment by pks-t** [comment]
Oh, forgot to adjust the commit messages. Thanks for noticing.

**Comment by ethomson** [comment]
@pks-t do you want to do the honors of tagging, or should I?

**Comment by pks-t** [comment]
I went ahead and tagget the release, thanks for merging. I would've done it a bit earlier, but I got a nice case of summer flu and today my ISP decided to turn off my internet access. Fun times :)

Please just have a quick look and verify whether the release looks good.

**Pull request merged**
