### PR TITLE
Replace fnmatch with wildmatch

### PR DESCRIPTION
**Pull request by pks-t**
Upstream git.git has replaced fnmatch with wildmatch back in commit 70a8fc999d (stop using fnmatch (either native or compat), 2014-02-15). wildmatch has different semantics than fnmatch has and thus may show slightly different behaviour than fnmatch. In fact, by replacing fnmatch with wildmatch, we fix compatibility with git.git in at least two places:

- gitignores and gitattributes now correctly handle patterns like "**.foo", which previously wouldn't match a file "x.foo"
- conditional includes now work (more?) consistently with how it works upstream

There's probably more compatibility improvements as fnmatch/wildmatch are used at various locations throught the tree, but only those two struck me while working on the replacement.

Anyway. Getting this merged will have to wait until @ethomson has determined whether we're even allowed to use "wildmatch.c" from git.git, depending on its license history.

### CODE REVIEW

**Comment by pks-t** [comment]
Fixes #5093

**Comment by pks-t** [comment]
Rebased to fix conflicts with #5097

**Comment by pks-t** [comment]
Fixes #5068

**Comment by ethomson** [comment]
Would you mind adding a paragraph to `COPYING`:

```
The bundled wildmatch code is licensed under the BSD license:

Copyright Rich Salz.
All rights reserved.

Redistribution and use in any form are permitted provided that the
following restrictions are are met:

1.  Source distributions must retain this entire copyright notice
    and comment.
2.  Binary distributions must include the acknowledgement ``This
    product includes software developed by Rich Salz'' in the
    documentation or other materials provided with the
    distribution.  This must not be represented as an endorsement
   or promotion without specific prior written permission.
3.  The origin of this software must not be misrepresented, either
    by explicit claim or by omission.  Credits must appear in the
    source and documentation.
4.  Altered versions must be plainly marked as such in the source
    and documentation and must not be misrepresented as being the
    original software.

THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by pks-t** [comment]
> Would you mind adding a paragraph to COPYING

Done!

**Comment by ethomson** [comment]
Nice one, thanks for this @pks-t!

**Pull request merged**
