### PR TITLE
Make binary detection work similar to vanilla git

### LINKED ISSUE #2651: Another CRLF issue
There seems to be another CRLF issue in 24deacb7ee7d4c77eaa4606afb21988d9fae8aa2.

Take the following file (LANG=JA, EOL=CRLF, ENCODE=UTF8+BOM; encoded in hex here to avoid transfer encoding issues):
EFBBBF4C414E473D4A412C20454F4C3D43524C462C20454E434F44453D555446382B424F4D0D0AE38193E38293E381ABE381A1E381AF0D0AE38193E38293E381B0E38293E381AF0D0A

At best set AUTOCRLF=true, clone https://github.com/csware/crlf-issue.git (and perform reset to HEAD) using libgit2 and you'll see the problem.

(msys)git behaves correctly and applies CRLF to the file when checking out.

### PR DESCRIPTION
**Pull request by csware**
Main change: Don't treat chars > 128 as non-printable (common in UTF-8 files)

cf. https://github.com/git/git/blob/master/convert.c#L33

Fixes #2651 and is more vanilla git centered than #2436

### CODE REVIEW

**Comment by csware** [comment]
Rebased.

**Comment by ethomson** [comment]
When you're changing a common utility function in the library that is used all over the place, I would really like to see a thorough list of who's impacted by it.  Especially since there's quite a difference between the git core code you link to (which is used *only* in CRLF filtering) and our code which is used more frequently and exported to callers.

So it's very much worth looking at who would be impacted by this change and not just changing this piecemeal without understanding the underlying differences between us and git core.

git core has a more common utility function, [`buffer_is_binary`](https://github.com/git/git/blob/398dd4bd039680ba98497fbedffa415a43583c16/xdiff-interface.c#L198)  is akin to our `git_buf_contains_nul`.  It's used:

1. In `git-merge`, [to produce a conflict during a three-way merge when the file is binary](https://github.com/git/git/blob/ce1d3a93a6405b8a0313491df3099919ed3d150f/ll-merge.c#L91).  We use [`git_blob_is_binary`](https://github.com/libgit2/libgit2/blob/master/src/merge.c#L1305) for our check, which calls `git_buf_text_is_binary`, which behaves differently already and is further impacted by this PR.

2. In `git-merge-file`, [to fail a three-way merge when the file is binary](https://github.com/git/git/blob/398dd4bd039680ba98497fbedffa415a43583c16/builtin/merge-file.c#L78).  We don't do this at all in `git_merge_file`.  (We probably should consider this.)

3. [To produce binary diffs / patches](https://github.com/git/git/blob/85f083786fe37f280ca30fc0b74498b22b322c6d/combine-diff.c#L1089).  We match this, in [`git_diff_driver_content_is_binary`](https://github.com/libgit2/libgit2/blob/091165c53b2bcd5d41fb71d43ed5a23a3d96bf5d/src/diff_driver.c#L414) by calling `git_buf_text_contains_nul`.  There's in fact a very topical comment:

         /* TODO: provide encoding / binary detection callbacks that can
          * be UTF-8 aware, etc.  For now, instead of trying to be smart,
          * let's just use the simple NUL-byte detection that core git uses.
          */

The function you link to in `convert.c` calculates the number of printable vs non-printable characters to determine binary-ness.  Interestingly, that function has a comment: `The same heuristics as diff.c::mmfile_is_binary()`.  This is no longer true, of course, since `mmfile_is_binary` doesn't exist, and when it did, it looked like `buffer_is_binary`.

This PR impacts `git_buf_text_is_binary`, which is used:

1. By `ident` to avoid filtering binary files.  This seems reasonable that it would use the same check that the CRLF filter uses (though, note that the git ident filter does not abort on binary files).
2. Exposed as `git_blob_is_binary`.  This seems reasonable that it would use the same check as the CRLF and ident filters.
3. Again, in `git_merge()`, when writing conflict files.  No regressions here, though again, git core simply uses the `is_nul` like check).
4. Also, in `git_checkout()`, when writing conflict files.

So, I'm willing to take this change.  Indeed it does seem to be in line with core git, and it does seem to be a helpful change to users.  Nor do I think that it should introduce any regressions.

If you wouldn't mind putting that long comment on its own line, or wrapping it or whatnot, that would be very nice.  Then I will merge this PR.

Apologies about the long delay.  Obviously we're all quite busy - one way to cut the time to get things merged down is to provide as much additional context as possible.  Maybe this means unit tests (I think this is why @carlosmn was suggesting this) and maybe this means explanation so that we understand what's changing and why.  This will ensure that changes require less deep inspection before they get merged and are, thus, merged much more quickly so that we don't have to find the time to study.

Anyway.  Thanks so much for this change, I think it's very helpful.  Again, if you wouldn't mind that minor formatting change, I'll be happy to merge it.

**Comment by ethomson** [comment]
Oops!  Also, if you wouldn't mind updating the `CHANGELOG` (in the `v0.22 + 1` section) to include this behavioral change, that would be great.  Something as simple as:

* Updated binary identification in CRLF filtering to avoid false positives in UTF-8 files.

That would be great.  Thanks again.

**Comment by csware** [comment]
@ethomson Updated. Hope I got you right...

**Comment by ethomson** [comment]
Manually merged.  Thanks!

**Pull request closed without merging**
