### PR TITLE
Correctly handle renames of submodules

### PR DESCRIPTION
**Pull request by csware**
Fixes issue #3365

### CODE REVIEW

**Comment by carlosmn** [comment]
Is there a test to show that this still lets us look up both by name and url? From this code, it looks like it would stop being available under the name.

**Comment by csware** [comment]
@carlosmn You are right. But if a submodule appears twice in the map it's also free'd twice.

**Comment by carlosmn** [comment]
I'm working on a refactor of the submodule lookup which should also solve this by splitting what each function does, but if you do have a test for this, it'd be great to have.

**Comment by csware** [comment]
See issue #3365 for an example where the current implementation fails

**Comment by swisspol** [comment]
See #3390 for another reproducible bug with submodules having their path different from their name.

**Comment by swisspol** [comment]
This patch fixes #3390 as well.

**Comment by carlosmn** [comment]
Superseded by #3370

**Pull request closed without merging**
