### PR TITLE
Fix Mac build without OpenSSL

### PR DESCRIPTION
**Pull request by leoyanggit**
If OpenSSL is disabled on Mac the SHA1 implementation goes to the CommonCrypto from the system. In this case we should not include the generic hash impl. Otherwise there would be duplicated impls which fail the build.

### CODE REVIEW

**Comment by carlosmn** [comment]
This feels like it's hiding the bug rather than fixing it. The Mozilla hash functions are the last ones to be chosen if nothing else has triggered. There should not be an OS-specific "IF" in our decision to use them.

**Comment by leoyanggit** [comment]
OK I updated my patch to make it look like hopefully better.

**Comment by carlosmn** [comment]
This adds complication just in order to have the CommonCrypto line where it currently is. It should instead be part of the normal decision making. We should not need to have a variable to tell us we already decided on an implementation. There should be a single place where we decide the implementation.

**Comment by leoyanggit** [comment]
How about add an `elseif cmake system name matches Darwin' branch with the definition of GIT_COMMON_CRYPTO inside right after the win32 if branch?

**Comment by leoyanggit** [comment]
I mean, and remove GIT_COMMON_CRYPTO definition from the current place.

**Comment by carlosmn** [comment]
Yes, we should change where the CommonCrypto selection currently happens and move to the if-else chain.

**Comment by leoyanggit** [comment]
OK, I updated the patch. Please have a look.

**Comment by carlosmn** [comment]
Thanks!

**Pull request merged**
