### PR TITLE
deps: ntlmclient: fix missing htonll symbols on FreeBSD and SunOS

### LINKED ISSUE #5414: Compile fails on FreeBSD with ld: error: undefined symbol: htonll
I maintain the libgit2 package for FreeBSD.

### Reproduction steps
Try to compile the new version 0.99.0 on FreeBSD.

### Expected behavior
It should compile.

### Actual behavior
Get a linker error:
```
ld: error: undefined symbol: htonll
>>> referenced by ntlm.c
>>>               deps/ntlmclient/CMakeFiles/ntlmclient.dir/ntlm.c.o:(ntlm_client_response)

ld: error: undefined symbol: htonll
>>> referenced by ntlm.c
>>>               deps/ntlmclient/CMakeFiles/ntlmclient.dir/ntlm.c.o:(ntlm_client_response)

ld: error: undefined symbol: htonll
>>> referenced by ntlm.c
>>>               deps/ntlmclient/CMakeFiles/ntlmclient.dir/ntlm.c.o:(ntlm_client_response)
```

You can find the full build log here:
https://pkg.fechner.net/data/121amd64-gitlab/2020-02-20_22h51m26s/logs/errors/libgit2-0.99.0.log

### Version of libgit2 (release number or SHA1)
0.99.0

### Operating system(s) tested
FreeBSD

### PR DESCRIPTION
**Pull request by pks-t**
The ntlmclient dependency defines htonll on Linux-based systems, only.
As a result, non-Linux systems will run into compiler and/or linker
errors due to undefined symbols.

Fix this issue for FreeBSD, OpenBSD and SunOS/OpenSolaris by including
the proper headers and defining the symbol accordingly.

---

We should probably merge this upstream first, but given that upstream means @ethomson I've decided to create the PR here first to let people in #5414 verify the fix more easily.

Fixes #5414

### CODE REVIEW

**Comment by ethomson** [comment]
> We should probably merge this upstream first, but given that upstream means @ethomson I've decided to create the PR here first to let people in #5414 verify the fix more easily.

Haha, yes, that's fine.  😁

**Comment by jacquesg** [comment]
Maybe see here to get this to work on Solaris 10:

https://github.com/esnet/iperf/pull/711/files

**Comment by pks-t** [comment]
Thanks a lot @jacquesg, I've amended my commit with your hint.

**Comment by pks-t** [comment]
@ethomson: will you apply my changes upstream or shall I create a PR for them?

**Comment by ethomson** [comment]
> @ethomson: will you apply my changes upstream or shall I create a PR for them?

I can take care of this - but looking again, should we be using `htobe64` on FreeBSD instead of `bswap64`?  The latter should swap regardless of endianness.

**Comment by pks-t** [comment]
On Tue, Feb 25, 2020 at 02:30:17PM -0800, Edward Thomson wrote:
> > @ethomson: will you apply my changes upstream or shall I create a PR for them?
> 
> I can take care of this - but looking again, should we be using
> `htobe64` on FreeBSD instead of `bswap64`?  The latter should swap
> regardless of endianness.

You're right probably. Does `htobe64` exist on FreeBSD?

**Comment by ethomson** [comment]
> You're right probably. Does `htobe64` exist on FreeBSD?

Allegedly: https://www.freebsd.org/cgi/man.cgi?query=byteorder&sektion=9

**Pull request merged**
