### PR TITLE
Fix broken links

### LINKED ISSUE #6570: URLs in example code are broken
The [`libgit2` example code](/libgit2/libgit2/tree/main/examples) has many URLs that do not point to anything anymore. 

For example, `README.md` contains this URL: http://libgit2.github.com/libgit2/ex/HEAD/general.html
The URL redirects to https://libgit2.org/

Here is another example, taken from [`general.c`](/libgit2/libgit2/blob/main/examples/general.c#L737-L744):

```c
/**
 * ### Config Files
 *
 * The [config API][config] allows you to list and update config values
 * in any of the accessible config file locations (system, global, local).
 *
 * [config]: http://libgit2.github.com/libgit2/#HEAD/group/config
 */
```

The URL (http://libgit2.github.com/libgit2/#HEAD/group/config) redirects to https://libgit2.org/#HEAD/group/config, which just shows the `libgit2.org` front page. 

1) Where might the information that the author intended be found?
2) The URLs should be corrected

### PR DESCRIPTION
**Pull request by csware**
fixes  #6570

### CODE REVIEW

**Comment by csware** [comment]
The tests are flaky.

**Comment by ethomson** [comment]
Why did libgit2.github.com break without any warning? I know that we were special cased or something to keep that domain but that's very annoying. @carlosmn any way you can find out what happened?

**Comment by ethomson** [comment]
It looks like all these links work again?

**Comment by csware** [comment]
No.

**Comment by ethomson** [comment]
Oh, I see, it's not preserving the path in the redirect. That's probably my fault from when I moved off Google Domains.

**Comment by ethomson** [comment]
Nope, it's GitHub, not including the path in our redirects. 🙃 

Can we update the links to `libgit2.org` instead of `github.io`?

**Comment by csware** [comment]
Done.

**Comment by ethomson** [comment]
Thanks!

**Pull request merged**
