### PR TITLE
add support for OpenSSL 1.1.0 for BIO filter

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Closes: https://github.com/libgit2/libgit2/issues/3959
Signed-off-by: Igor Gnatenko i.gnatenko.brain@gmail.com

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
P.S. I didn't test it yet

**Comment by carlosmn** [comment]
I would rather have us `#define` these `BIO_` setters and getters if we detect that OpenSSL doesn't provide them so we don't have our code littered with preprocessor statements.

**Comment by mikeando** [comment]
No need to use a `#define`, real functions will work just fine. Just add a compatibility header that only defines the functions if SSH isn't providing them.

~~~
#if !OPENSSL_HAS_BIO_SET_INIT
void BIO_set_init(BIO* b, int v) {
 	b->init = v;
 	b->num = 0;
 	b->ptr = NULL;
 	b->flags = 0;
}
#endif
~~~

etc.

**Comment by carlosmn** [comment]
Declaring functions in someone else's namespace is something you have to be very careful about, or you might end up overwriting the one hat libssl itself provides, depending on exactly how the libraries are loaded, like in the example above.

**Comment by ignatenkobrain** [comment]
so what should I do after all?

**Comment by carlosmn** [comment]
Either would work, but if you prefer functions, they should be using the `GIT_INLINE` macro so they're local and the compiler is more likely to inline these single-use tiny functions.

**Comment by carlosmn** [comment]
My distribution just upgraded to 1.1 in the headers, so I've gone ahead and updated to what the kind of interfaces we program against.

I also moved the creation of the method to the global initialisation function. Creating a new one on each connection is unsafe thread-wise and it's also a memory leak.

**Comment by carlosmn** [comment]
Thanks for doing the 1.1 conversion.

**Pull request merged**
