### PR TITLE
Mention field addition in breaking API changes

### PR DESCRIPTION
**Pull request by simonbyrne**
`proxy_opts` fields were added to 2 structs, but not mentioned in the CHANGELOG. Cross ref https://github.com/JuliaLang/julia/issues/19793.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Also `git_merge_options` change was in the wrong section.

**Comment by simonbyrne** [comment]
The release notes (https://github.com/libgit2/libgit2/releases/tag/v0.25.0) should probably be updated as well, but this can't be done via a PR>

**Comment by ethomson** [comment]
The `git_merge_options` change was in the correct section.  That change landed in 0.24.4.  Can you revert that change?

**Comment by ethomson** [comment]
Thanks for updating this.  I'll also update the release notes on the web page.  I'll open a PR to backport this to `maint/v0.25`.

**Pull request merged**
