### PR TITLE
Dont update index unnecessarily

### PR DESCRIPTION
**Pull request by ethomson**
Now with unit test goodness.

### CODE REVIEW

**Comment by carlosmn** [comment]
I was really hoping for fewer sleeps. I'm working on exposing the index' trailer so we should be able to read it and compare an oid instead of relying on timestamps.

**Comment by ethomson** [comment]
Sleeps in tests are horrible.  That would be great.

**Comment by ethomson** [comment]
Well, the problem with using the checksum is that the checksum will be updated when the contents of the file changes.

This change is attempting to ensure that we're not unnecessarily rewriting indexes when they *haven't* changed.  In that case, we're dumping an index that would have the same checksum, so it seems that the only way to identify that is to let the clock tick.

Of course we may be able to `usleep` if we have a more granular `p_stat`.

**Comment by ethomson** [comment]
(Note this requires #3226 since we are currently rewriting the index in the second diff.)

**Comment by carlosmn** [comment]
I think we should still be able to detect changes without using sleep. If we set the index file's timestamp forward five seconds and then instead of `touch_file` we move the file's mtime six seconds forward, we should be able to detect that the index was rewritten because stating it afterward would have changed the timestamp on disk.

Or we can move the index file's timestamp backwards, so we know we won't accidentally take long enough in the test for us to catch up to whatever much we moved it forward.

**Comment by swisspol** [comment]
Thanks for writing the unit tests @ethomson!

**Comment by ethomson** [comment]
Updated to manipulate timestamps and investigate the index's checksum to determine changedness.  So this should perform the same function and avoid `sleep`s.

**Pull request merged**
