### PR TITLE
Test library init/shutdown separately

### PR DESCRIPTION
**Pull request by tiennou**
As it says on the tin. The goal is to see how we fare when the library goes through multiple init/shutdown cycles.

### CODE REVIEW

**Comment by tiennou** [comment]
Since clar modifications are supposed to go upstream (when possible), I'll kindly ask for @vmg's review of the clar parts.

**Comment by pks-t** [comment]
Just to let you know: we already have the tests that you propose in "core::init".

**Comment by tiennou** [comment]
Almost ? I'm looking at what happens after "something" really happens (like, we do some cloning, which might involve TLS, which might have some global object). If I can get the suite to got past a double-free in "core::useragent".

**Comment by pks-t** [comment]
Oh, I see. Shouldn't have jumped to conclusions from the PR's description only ;)

So what you are doing here is executing `git_libgit2_init`/`git_libgit2_shutdown` after each test suite. Two questions which were popping into my mind: What is the performance impact of this and why is it being executed after each suite and not after each test? Performance reasons?

**Comment by tiennou** [comment]
Yep, sorry for the almost-scription.

From a performance POV it didn't seem to add that much locally, but I'll try to provide hard data if you want (as soon as I can get a complete test run 😂). Right now local/Travis segfaults in `core::useragent`, and AppVeyor is unhappy for different reasons.

I chose to go the "setup/teardown for each suite" because that was a little more specific, without being too frequent, but it could be changed easily if you want.

**Comment by ethomson** [comment]
Curious about the impetus behind these tests.  I don't think that we've ever said that you could `git_libgit2_init` after you've shutdown.  We're jumping into testing that its successful without thinking about what it means to make this guarantee and whether it's a desirable thing for the library to enable.

**Comment by tiennou** [comment]
Well, I wasn't aware of `init/shutdown` being a process-lived thingy, so I can understand why this is surprising… The rationale was making sure we behaved correctly w.r.t memory-management and the library lifecycle under various workloads (various workloads being simulated individual test runs).

**Comment by ethomson** [comment]
OK, cool.  I'd be curious to see where these test failures are - the user agent thing seems like an obvious double-free that we can and should fix.  So I'm hopeful that all of the issues are like this.  But if there are hard problems that stem from our assumptions about lifecycles, then I think we should consider how to proceed.

**Pull request closed without merging**
