### PR TITLE
Add NO_PROXY env support

### PR DESCRIPTION
**Pull request by sathieu**
Item 2 of 3 from #4164.

Note that the behavior is same as wget (and not same as curl). Some examples:
- `"192.168.1.1"`: Matches exactly the given IP
- `"192.168.1.1:8080"`: Matches exactly the given IP and port
- `"example.com" `: Matches exactly the domain example.com
- `"example.com:8080" `: As above, restricting port (handle default ports)
- `".example.com"`: Matches every machine in the example.com domain. But NOT example.com (like curl, wget also includes example.com).
- `".example.com:8080" `: As above, restricting port (handle default ports)
- `".example.com,example.com"`: Matches every machine in the example.com domain and example.com
- `"foo.example.com"`: Matches exactly the foo.example.com machine
```
Wildcards a have no special meaning (i.e. "*.example.com" won't match anything).

### CODE REVIEW

**Comment by sathieu** [comment]
It looks like Windows is unable to read empty env var:
```
   1) Failure:
6: online::clone::proxy_credentials_in_environment [D:\a\libgit2\libgit2\tests\online\clone.c:872]
6:   Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo", &g_options))
6:   error -1 - could not read environment variable 'no_proxy': 
```

(See https://github.com/libgit2/libgit2/runs/1885965142?check_suite_focus=true#step:7:3127).

Done this:
```diff
diff --git a/tests/online/clone.c b/tests/online/clone.c
index b1c59b3d4..ce581d89d 100644
--- a/tests/online/clone.c
+++ b/tests/online/clone.c
@@ -867,7 +867,7 @@ void test_online_clone__proxy_credentials_in_environment(void)
 
        cl_setenv("HTTP_PROXY", url.ptr);
        cl_setenv("HTTPS_PROXY", url.ptr);
-       cl_setenv("NO_PROXY", "");
+       cl_setenv("NO_PROXY", NULL);
 
        cl_git_pass(git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo", &g_options));
 
```

**Comment by sathieu** [comment]
@ethomson Please review :eyes:.

**Comment by sathieu** [comment]
@ethomson Would you review this?

**Comment by ethomson** [comment]
Hi @sathieu!  Thanks for the pull request.  Sorry for the delay, I've been quite busy with work and home responsibilities.  I'll try to take a look 🔜

**Comment by sathieu** [comment]
@ethomson I've rebased. Could you please review?

**Comment by sathieu** [comment]
@ethomson Please review. We're using this patch without problems since months.

I've added support for `*.example.com` with same behavior as `.example.com`, as some of my colleague use this syntax.

**Comment by sathieu** [comment]
@ethomson Please review this PR. As you look busy: can someone else review?

**Comment by Ragatzino** [comment]
I have the same issue, could you please merge? :)

**Comment by sathieu** [comment]
@ethomson Any chance to have this merged in 1.2?

**Comment by ethomson** [comment]
@sathieu I was actually looking at this last night.  I'll suggest some refactorings to reduce the amount of pointer arithmetic and use some of our existing utility functions instead, but yes, I think that we should land this for 1.2.

**Comment by ethomson** [comment]
Merged in #6026 with some refactorings to support the other issues in #4164 - thanks, @sathieu!

**Comment by sathieu** [comment]
Thanks @ethomson :+1:!

**Pull request closed without merging**
