### PR TITLE
WinHTTP for MinGW

### PR DESCRIPTION
**Pull request by tkelman**
Rebased #2414 and added in the pieces of the other patches from that thread that were necessary to build locally ~~(have only tested with i686-w64-mingw32 so far)~~, plus a couple of little fixes of my own. Hopefully I didn't screw up the conflict resolution here too badly.

### CODE REVIEW

**Comment by tkelman** [comment]
There appear to be some issues here in cross-compilation which I will take a look at.

@claudiuolteanu or @akikoskinen, if either of you have any input here let me know.

**Comment by carlosmn** [comment]
AppVeyor and Travis seem happy, so we should probably merge it, @ethomson ?

**Comment by ethomson** [comment]
I'm sorry to see us drop `StringCbPrintfW` in favor of a simple `wsprintf`.  Does mingw not have `wsprintf_s`?

**Comment by tkelman** [comment]
It looks like it does not, though mingw-w64 does have `strsafe.h` afaict.

**Comment by tkelman** [comment]
I just pushed a sort-of messy ifdef version that uses `strsafe.h` on MSVC or MinGW-w64, but not on mingw.org. I'm starting to think it might be cleaner to handle all of `strsafe.h`, `urlmon.h`, and `winhttp.h` via `CHECK_INCLUDE_FILES` in cmake...

**Comment by ethomson** [comment]
I don't think you can switch quite so easily.  The `strsafe` type functions return an `HRESULT`, not an int with the number of chars written.  I think you can switch between `wsprintf_s` and `wsprintf`.  But if this is overly burdensome, I don't know that it's necessarily worth doing.

The one thing I might do is try to bring that define a little closer to the `printf` so that it's a little clearer that there's risk of overflows if you change it.

**Comment by tkelman** [comment]
> The `strsafe` type functions return an `HRESULT`, not an int with the number of chars written.

Whoops, yeah, you're right.

> The one thing I might do is try to bring that define a little closer to the `printf` so that it's a little clearer that there's risk of overflows if you change it.

Sorry, which define?

**Comment by ethomson** [comment]
> Sorry, which define?

Sorry, that was a wholly incomplete thought on my part.

It wasn't immediately obvious to me that `UUID_LENGTH_CCH` was the length of the resultant string from the `printf` at https://github.com/tkelman/libgit2/blob/mingw_winhttp/src/transports/winhttp.c#L1015

Fundamentally, I think that's probably okay, especially in the current version that uses `wsprintf_s` everywhere that it can.

(And oops, I realize now that's _swprintf_s_.  Sigh.  We just *mangle* posix names at Microsoft.)

**Comment by tkelman** [comment]
> (And oops, I realize now that's swprintf_s. Sigh. We just mangle posix names at Microsoft.)

Heh. The MSVC failure on appveyor made me realize that one. And looking at the mingw-w64 headers, I think `swprintf_s` should probably also be keying off of `MINGW_HAS_SECURE_API`.

And I'm overly rebase-and-force-push-happy here, so I think that line number may have changed under you. I like hitting `y` to make github add a sha so the link stays useful.

**Comment by tkelman** [comment]
Pretty sure the OSX Travis failure is unrelated. (Our OSX builds time out a lot on Julia too, so it's not just you. From checking cpuinfo, the builds are running on 5-year-old hardware, probably oversubscribed. Anyone know of a faster hosted OSX CI service?)

Any other feedback on what is mostly @phkelley's code?

**Comment by ethomson** [comment]
This looks good to me.  Thanks for this (and thanks to @phkelley as well).

**Pull request merged**
