### PR TITLE
pkgconfig: do not quote Libs

### PR DESCRIPTION
**Pull request by ignatenkobrain**
It doesn't make sense at all.

### CODE REVIEW

**Comment by bapt** [comment]
:+1: we have the same issue on FreeBSD

**Comment by pks-t** [comment]
Well, I'm not too sure about this. While I'd also say that the quotes should in fact not be necessary, they have been explicitly added #3569. This is related to Windows build failures with rugged, see libgit2/rugged#559 and 835be6c.

Any comments, @arthurschreiber @mscharlye?

**Comment by mscharley** [comment]
My only comment is that it's not only necessary on Windows, just more likely to be an issue there. GCC and friends (at least under mingw) treat this file as a list of shell arguments, hence the quoting to ensure that paths with spaces or other similar meta characters in them work correctly. Perhaps a solution that might work is moving the open quote to the start of the parameter instead of starting the quote half-way through the option which is something that works in shell, but may not work so well in other systems.

If that still doesn't help, it seems like an incompatibility between different tool chains and I'm not really proficient with C tool chains so I'm not sure how much more help I can be.

**Comment by pks-t** [comment]
A short test shows that we shouldn't actually require quotes at all:

```
cat >/tmp/whitespace.pc <EOF
prefix=/usr
exec_prefix=${prefix}
libdir="${exec_prefix}/white space/lib"

Name: whitespace test
Description: whitespace description
Version: 1
Libs: -L${libdir}
EOF
```

On command line:

```
$ PKG_CONFIG_PATH=/tmp pkg-config --libs whitespace
-L/usr/white\ space/lib
```

So pkg-config should automatically escape whitespace here, if I'm not mistaken.

**Comment by ethomson** [comment]
@pks-t What platform did you just test?  Is that cygwin?

**Comment by mscharley** [comment]
Testing with mingw:

```
libdir="${exec_prefix}/white space/lib"
Libs: -L${libdir}
# Gives...
$ pkg-config --libs whitespace
-L/usr/white\ space/lib
```

```
libdir=${exec_prefix}/white space/lib
Libs: -L${libdir}
# Gives...
C:\Ruby22-x64\DevKit-mingw64-64-4.7.2\tmp $ pkg-config --libs whitespace
-L/usr/white space/lib
```

```
libdir=${exec_prefix}/white space/lib
Libs: -L"${libdir}"
# Gives...
C:\Ruby22-x64\DevKit-mingw64-64-4.7.2\tmp $ pkg-config --libs whitespace
-L/usr/white\ space/lib
```

Looks like the right solution could be to move the quoting to the `libdir` declaration instead of deleting it entirely - seems to work for everyone.

**Comment by pks-t** [comment]
I agree that quoting libdir is the right thing to do here

**Comment by ethomson** [comment]
@ignatenkobrain  Are you able to make this change to quote libdir and test on your platform?

**Comment by ethomson** [comment]
Closing in favor of #4193

**Pull request closed without merging**
