### PR TITLE
examples: Free the git_config and git_config_entry after use

### PR DESCRIPTION
**Pull request by 257**

### CODE REVIEW

**Comment by ethomson** [comment]
Good catch!  Thanks for the fix.  😀

**Comment by 257** [comment]
do i get a credit for it? :)

i noticed Author: header, in the commit log, is set to this:
`Author: Edward Thomson ***@***.***>`

other projects usually use the Committer/Autor pair.

**Comment by ethomson** [comment]
I'm not sure what you mean.

Screen Shot 2021-09-27 at 16 07 17

Your commit has your committer and author information, which is what you pushed up:

```
% git cat-file commit 581cfbd
tree 48803cd33cc63c03015446332b04789b3a9e81a7
parent 136901086ecfdd2b5cc106782310355a9c0b1a9a
author Paymon MARANDI <darwinskernel@gmail.com> 1632412792 -0400
committer jrun <darwinskernel@gmail.com> 1632507299 -0400
```

**Comment by 257** [comment]
>  git cat-file commit 581cfbd

i see, thanks. i was looking at `git cat-file commit 424812e3d874`.
actually you're doing it different from others; what's the workflow here, i mean if you have time to explain.

**Pull request merged**
