### PR TITLE
Document that a commit is not a descendant of itself

### PR DESCRIPTION
**Pull request by jacwah**
See issue #3780.

### CODE REVIEW

**Comment by pks-t** [comment]
Hi @jacwah, and thanks for your first PR!

I agree that we should at least document that behaviour when it deviates from git.git, so this is definitly a good change. Two comments regarding the change itself:

* the documentation should probably not be part of the return code, but rather of the function documentation's body. See for example how it's done for the preceding function `git_graph_ahead_behind`, where additional information on its behaviour is given after the initial short heading.
* it would be nice if you could prefix the commit message's first line with the scope it applies to. E.g. in this case "graph: document that a commit isn't a descendant of itself".

**Comment by jacwah** [comment]
@pks-t Thanks for the feedback! I updated the PR to your suggestions.

Writing the original commit message, I had a hard time cramming everything into 50 characters (recommended max length). If that limit is softer, your suggestion is obviously superior.

**Comment by pks-t** [comment]
Yeah, the 50 characters limit is simply impossible to fulfill in many cases. We try to be as short as possible here, but I guess it's okay to get to ~75 characters.

**Comment by pks-t** [comment]
I'd still propose that you move the note from the `@return` annotation to between summary and the first `@param`. So

```
/*  Determine if a commit...
 *
 * Your note on descendants here
 *
 * @param...
 * ...
 */
```

This matches existing style more closely and is a bit easier to spot, I guess.

**Comment by jacwah** [comment]
@pks-t Sorry! I didn't commit the changes properly. Should be ok now.

**Comment by pks-t** [comment]
Looks good now, thanks a lot!

**Pull request merged**
