### PR TITLE
examples: Add '-i' option for log

### PR DESCRIPTION
**Pull request by JIghtuse**

### CODE REVIEW

**Comment by carlosmn** [comment]
This has the same issue as #3189; `strcasestr` only exists in some places.

**Comment by JIghtuse** [comment]
Oh, I haven't noticed this PR.
@carlosmn good notice, I didn't thought about it. Will investigate strcasestr availability on different platforms.

**Comment by ethomson** [comment]
Indeed we do need to make sure that our examples compile across platforms. It's much more important to illustrate driving libgit2 than necessarily providing useful examples. For housekeeping purposes, I'm going to close this, since there hasn't been any movement here recently, but please do reopen if you'd like to continue to work on it.

**Comment by Therzok** [comment]
> For housekeeping purposes, I'm going to close this, since there hasn't been any movement here recently, but please do reopen if you'd like to continue to work on it.

Still open. :dancer:

**Pull request closed without merging**
