### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BirdboyBolu**

### CODE REVIEW

**Comment by extrawurst** [comment]
its probably good to provide some context of why these changes should be considered

**Comment by BirdboyBolu** [comment]
Hello @extrawurst, I changed a few passive words to action words. The changes were little and I am still looking through more. I wanted to give a description at the end. Thank you

**Comment by extrawurst** [comment]
> I wanted to give a description at the end.

@BirdboyBolu its best practice if its work in progress to mark the PR as *draft* so no one ends up doing unnecessary feedback

**Comment by carlosmn** [comment]
This is more than stylistic changes. There are deeper changes to meaning here.

**Comment by ethomson** [comment]
Indeed. Is it ideal for powering things? Sure, I guess, but that's fluffy and subjective. That it *does* power things is objective and worth celebrating.

If you're interested in iterating on this then I will leave this PR open, but these changes are not an improvement over what's there, as they stand.

**Pull request closed without merging**
