### PR TITLE
Reflog/Parse skip newlines at the end of last message.

### PR DESCRIPTION
**Pull request by lolgear**
- [x] #5262 

It is done by seek forward to a character that following after invalid character.

```c
if (get_oid_old < 0) {
  // get invalid character position
  int position = get_position();
  seek_forward(position + 1);
}
```

### CODE REVIEW

**Comment by pks-t** [comment]
Thanks a lot for your pull request! I've taken a deeper look at the code to try to find out the root cause. The issue is that we do not sanitize entries that we're adding to the reflog ".git/logs/refs/stash". As a result, if the user specifies multi-line reflog messages, the reflog will end up with these exact newlines and thus break the format.

So two things that need to be done:

1. libgit2 needs to sanitize reflog messages in all places properly
2. We should just skip over non-parseable lines in the reflog. Git itself does so, we should do the same.

I'll open a PR in a few minutes that tackles both these issues. I hope you don't mind me effectively taking over the issue, but I think that the deeper underlying issues need to be fixed. Anyway, thanks a lot for bringing this to our attention and proposing a fix!

**Comment by pks-t** [comment]
Please see #5275

**Comment by ethomson** [comment]
Closed via #5275.  Thanks for reporting this issue and the collaboration to fix it.

**Comment by lolgear** [comment]
Fixed in #5275

**Pull request closed without merging**
