### PR TITLE
More `safe.directory` improvements

### PR DESCRIPTION
**Pull request by ethomson**
The gift that keeps on giving — it will rival `core.autocrlf` for user disappointment.

A number of changes here:

1. We ensure that we cope correctly with `%(prefix)` in front of paths.
2. We stop requiring that UNC paths start with `%(prefix)`
3. Report the directory path without a trailing slash
4. Ensure that root paths are correctly handled
5. Ensure that the repository path is canonicalized on Windows — we were already doing this on POSIX, and this aligns with Git itself
6. To cope with this, we need to start canonicalizing the clar sandbox paths so that the repository path is deterministic and we can continue joining paths simply

### CODE REVIEW

**Comment by ethomson** [comment]
The gift that keeps on giving — it will rival `core.autocrlf` for user disappointment.

A number of changes here:

1. We ensure that we cope correctly with `%(prefix)` in front of paths.
2. We stop requiring that UNC paths start with `%(prefix)`
3. Report the directory path without a trailing slash
4. Ensure that root paths are correctly handled
5. Ensure that the repository path is canonicalized on Windows — we were already doing this on POSIX, and this aligns with Git itself
6. To cope with this, we need to start canonicalizing the clar sandbox paths so that the repository path is deterministic and we can continue joining paths simply

**Comment by ethomson** [comment]
Fixes #6737

**Comment by csware** [comment]
As another improvement, the error message should provide the `%(prefix)/` as vanilla Git does.

A fix would also be nice to have for 1.7.3

**Comment by ethomson** [comment]
> As another improvement, the error message should provide the %(prefix)/ as vanilla Git does.

Right - sorry - I went back to your PR and realized that I never actually finished typing up the comments. We need to avoid multi-line error messages since some people use them in odd places. I don't have a great idea for how to plumb this through (the directory that's problematic vs the configuration command that you would run). This _feels_ like a good use for the "warnings API" that we keep talking about and never shipping, so let me give it some thought.

**Comment by ethomson** [comment]
I'm willing to back port to v1.7, but I'm also preparing to cut v1.8 if that makes more sense for you.

**Comment by csware** [comment]
I'm testing the main branch right now...

**Comment by csware** [comment]
> > As another improvement, the error message should provide the %(prefix)/ as vanilla Git does.
> 
> Right - sorry - I went back to your PR and realized that I never actually finished typing up the comments. We need to avoid multi-line error messages since some people use them in odd places. I don't have a great idea for how to plumb this through (the directory that's problematic vs the configuration command that you would run). This _feels_ like a good use for the "warnings API" that we keep talking about and never shipping, so let me give it some thought.

I'm not talking about presenting the git command to use (which may not make any sense if Git is not installed). Just printing: this is the path you need to whitelist.

**Pull request merged**
