### PR TITLE
Remove `core.autocrlf` and CRLF filtering

### PR DESCRIPTION
**Pull request by ethomson**
With the upcoming Windows 10 and Visual Studio 2015 releases supporting a single `\n` (ASCII `0x0a`) in all their tooling, CRLF filtering in Git becomes unnecessary.  Turn CRLF filtering off entirely, such that `core.autocrlf` is a noop and the `text` attribute doesn't mangle your files.

This removes many of our most pernicious and longest standing bugs (including ones we haven't even found yet) and eases the [single](http://stackoverflow.com/questions/11534035/git-crlf-for-windows-users) [largest](http://stackoverflow.com/questions/2825428/why-should-i-use-core-autocrlf-true-in-git) [customer](http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git) [pain](http://stackoverflow.com/questions/4181870/git-on-windows-what-do-the-crlf-settings-mean) [point](http://stackoverflow.com/questions/2016673/definitive-recommendation-for-git-autocrlf-settings) [in](http://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf) [Git](http://stackoverflow.com/questions/3206843/how-line-ending-conversions-work-with-git-core-autocrlf-between-different-operat) amongst Windows users.

### CODE REVIEW

**Comment by ethomson** [comment]
On a personal note, this sadly shutters my new business as a [Git Therapist](https://twitter.com/ethomson/status/575289884794994688).  However I trust that I can pivot into the lucrative market of therapy for people scarred by OpenSSL.

**Comment by linquize** [comment]
What happens if user still using old tools, old platforms?

**Comment by rhuijben** [comment]
Good question. It is unlikely that everybody will just immediately upgrade. I'm guessing that it will take a few years before my users are on these versions. (Usually the majority leaps behind a bit on at least some of their tooling)

**Comment by rhuijben** [comment]
But with today's date, maybe thus is just released frustration.

**Comment by nulltoken** [comment]
This PR adds so much value through removal.

**Comment by linquize** [comment]
For example, does Windows 10 notepad displays `\n` correctly?
Should we also check Windows version?

**Comment by Therzok** [comment]
This is not an April Fools, right?

**Comment by linquize** [comment]
Do you cut `.gitattributes` text attribute?

**Comment by ch3cooli** [comment]
@csware Do you notice this PR?

**Comment by csware** [comment]
I would love if git would never had implemented this, but git has this feature and we've to deal with it :(

@ethomson Not all people are using (latest) M$ software, people might also use other software which has problems with LF-only EOL

**Comment by carlosmn** [comment]
As much as I believe this is a Just and Right thing to do, we must remain bug-compatible for some of the more gregarious ones that people have come to rely upon, like the ridiculous ignore system and the fact that a content tracking system will transparently guess that some files need to be passed though an imperfect filter that guesses that one byte should be a couple of bytes, because Reasons.

**Comment by ethomson** [comment]
"A lie that is half-truth is the darkest of all lies." - Tennyson.  Which is to say...



Sorry to get your hopes up.  (Or make you think that I might have totally lost it.)
 


That said, CRLF is a pox upon all of our houses and we should think seriously about how to fix some of these problems.  (And no, it's quite obvious to everyone that this can't just be a unilateral delete a bunch of code and hope for the best, much as I wish it were that easy.)

**Comment by rhuijben** [comment]
:+1:

**Comment by YueLinHo** [comment]
OH~ I was fooled. :-)

**Comment by csware** [comment]
https://www.youtube.com/watch?v=kXYXuXX48m8 ;)

**Pull request closed without merging**
