### PR TITLE
mkdir-ext: Assume directories don't exist; fix all race cases

### PR DESCRIPTION
**Pull request by vmg**
Here's an alternate take on https://github.com/libgit2/libgit2/pull/2988 which fixes the original race + the case where we race because the file gets removed. I think this is less/clearer code too.

@simonsj: can you confirm this fixes your issue?
@carlosmn: can you review please?

### CODE REVIEW

**Comment by vmg** [comment]
# :tada:  :tada:  :tada:  :tada: 3000 PRs :tada: :tada:  :tada:  :tada:

**Comment by ethomson** [comment]
Nice!  But dropping that `lstat` will regress the Mac OS case insensitivity `.git` symlink bug.  :(

**Comment by vmg** [comment]
Wait, to `mkdir` and `lstat` don't have the same "open" semantics? Are you sure about that? Are computers this fucking shitty?

**Comment by simonsj** [comment]
At a glance I think this may work -- instead of doing `stat`, `mkdir /* with EEXIST check */`, `re-stat`, as in #2988 this version skirts the original stat with a `mkdir`.

I was deliberately conservative in the original patch to ensure I didn't change the semantics of the existing codepath: in other words #2988, a new codepath would only be hit for the case that the race was hit.

That said if this should work, too, and [the case-sensitivity](https://github.com/libgit2/libgit2/pull/3000#issuecomment-83674137) is not an issue I'd be happy with this fix.

**Comment by ethomson** [comment]
I don't really remember offhand and I would have to think a bit more about this.  (I think that there may be a deficiency here in that you can't assume that `EEXISTS` means that it's *a directory* that exists and not a symlink...)

Let me re-read that pull request and let me try to remember what I was thinking with `stat` / `mkdir` instead of just a `mkdir`.

**Comment by vmg** [comment]
@ethomson: I gave it another go trying not to change the existing semantics. This one "feels" better to me despite de goto, because it's essentially the same code.

**Comment by simonsj** [comment]
:+1: on d88e6e9b3c9dd27644083b157bb28a42d670ed24 from me, FWIW.

Despite the backwards `goto` I think it's the cleanest phrasing available in this context.  I'd avoided that initially per request [here](https://github.com/libgit2/libgit2/pull/2988#issuecomment-81968300).

It's also good we're retaining the (minor) fix from the other patch for the `opts->perfdata.mkdir_calls++;` which previously might have been incremented for some cases where no `mkdir` would actually be called.

**Comment by ethomson** [comment]
Yeah, I think this makes sense.  Thanks.

To capture this here, the `lstat` / `mkdir` dance is two calls in the general create-a-directory case, but it represents a net reduction of syscalls in the checkout case (which is where it's most important, since you're repeatedly being asked to create the same directory structure over and over again[1], so being asked to make the same directory is a single `lstat` instead of a `mkdir`, catch the failure, then call `lstat` to get more details.)

[1] Note that we do some caching of the directory structure in checkout now, so this two-step process may not be helpful anymore.  But I'd like to profile that before I remove it outright.

**Comment by vmg** [comment]
@simonsj: ship it!

**Comment by ethomson** [comment]
3000th_pr

**Comment by vmg** [comment]
I *really* appreciate that gif.

**Comment by ethomson** [comment]
I learned photoshop just so I could.

**Pull request merged**
