### PR TITLE
travis: fetch trusty dependencies from Bintray

### PR DESCRIPTION
**Pull request by ethomson**
I would like to host the trusty dependencies in an Azure Web App - currently I'm hosting them on a linux VM in Azure.  This is a lower-cost option that hurts my pocketbook less.

### CODE REVIEW

**Comment by ethomson** [comment]
Ugh.  There's something about Azure Web Apps where they include a `Content-Type` header for files with no extensions, and apt (at least, trusty's version of apt) decides that's not cool.  (Sigh.)  I have yet to find a way to disable the `Content-Type` header.  I'll keep poking at this.

**Comment by ethomson** [comment]
Okay, well, I've given up on Azure.  It seems that GitHub Pages can handle this properly!

**Comment by ethomson** [comment]
Okay, let's try Bintray!  😀

**Comment by carlosmn** [comment]
Your GPG key won't be very useful as I'm having bintray sign it themselves (we could have a specific bintray gpg key, and upload via API so we can provide the passphrase but this seems easier).

**Comment by ethomson** [comment]
Can confirm this setup is 👍 on my trusty box.  Hopefully travis agrees.

**Comment by carlosmn** [comment]
The only missing bits for green CI is the macOS build which isn't affected by this, so I'm just going to merge it.

**Comment by pks-t** [comment]
Adding the backport label as we need this to fix CI builds on maint

**Pull request merged**
