### PR TITLE
submodule: refactor to be more explicit in the search

### PR DESCRIPTION
**Pull request by carlosmn**
When searching for information about a submdoule, let's be more explicit
in what we expect to find. We currently insert a submodule into the map
and change certain parameters when the config callback gets called.

Switch to asking for the configuration we're interested in, rather than
taking it in an arbitrary order.

---

Not as many minuses as I'd hoped, but a bunch of the code is rather repetitive. This may handle #3365 as a side-effect, but there's currently no test for explicitly such a case.

### CODE REVIEW

**Comment by carlosmn** [comment]
This does solve #3365 though I don't know how to reproduce the situation. There does not seem to be anything different about the submodules which don't have the correct path.

**Comment by csware** [comment]
@carlosmn Yeah, issue #3365 is about the order in which the config sections are returned by `git_config_file_foreach`. If `submodule.X.url` is before `submodule.X.path` (or vice versa, don't remember right now) then the issue arises.

**Comment by carlosmn** [comment]
All of those submodule configs you show on that issue have the path before the url, so that doesn't look like it.

I have tested it against the repository in question and it does fix it, but the original cause for the error is still unclear.

**Comment by csware** [comment]
@carlosmn I'm really sure that it is the order, I debugged the old code step by step.

**Comment by swisspol** [comment]
See #3390 for another reproducible bug with submodules having their path different from their name.

**Comment by csware** [comment]
Any ETA for this?

**Comment by carlosmn** [comment]
There's a bug reported against it with no unit test, so it'll take as long as it takes to reproduce, fix and review.

**Pull request merged**
