### PR TITLE
Don't fail the whole clone if you can't find a default branch

### PR DESCRIPTION
**Pull request by torvalds**
In commit 6bb358786 ("clone: set refs/remotes/origin/HEAD to default
branch when branch is specified, attempt 2") libgit2 was changed to set
the default remote branch when one was copied.

But it makes update_head_to_branch() return an error if the origin
doesn't even *have* a HEAD in the first place, since
git_remote_default_branch() will fail.

That seems entirely wrong, and means that you cannot do "git_clone()" of a
particular branch on a remote repository when that remote doesn't have a
default branch at all.

So don't set the error code.

Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

### CODE REVIEW

**Comment by torvalds** [comment]
This is my trivial suggested fix for

        https://github.com/libgit2/libgit2/issues/6368

but honestly, I don't really know the code, so somebody should verify.

**Comment by torvalds** [comment]
Adding @ethomson @A-Ovchinnikov-mx who were involved with writing and merging the change that seems to have caused the problem.

**Review by moerradi — DISMISSED** [review]
Good job bro

**Comment by ethomson** [comment]
Oh, I forgot to mention @torvalds - we have a number of integration tests that talk to various hosting providers -- I'm also happy to add a test that talks to subsurface directly if we could get an account for testing that is read-only.

**Pull request merged**
