### PR TITLE
Rename FALLBACK to UNSPECIFIED

### PR DESCRIPTION
**Pull request by carlosmn**
Fallback describes the mechanism, while unspecified explains what the
user is thinking.

### CODE REVIEW

**Comment by ethomson** [comment]
Dumb question: should the default value be `DEFAULT` and not `UNSPECIFIED`?

**Comment by arthurschreiber** [comment]
:+1: for `DEFAULT`.

**Comment by carlosmn** [comment]
The default would indeed be named `_DEFAULT` but this is not what we're expressing here. What we're expressing is that we do not want to override the value at the level which is specified. It does not mean that we're going to use the default, as there may be a setting lower down.

**Comment by ethomson** [comment]
Got it.  Thanks for the clarification.

**Pull request merged**
