### PR TITLE
Fix for issue #3105: usage of SecCopyErrorMessageString and libssh2 search path

### PR DESCRIPTION
**Pull request by logancollins**
This pull request includes a fix for issue #3105. Namely, it fixes usage of the SecCopyErrorMessageString() function on iOS (where it's not available) by ifdef'ing out the relevant block in favor of just logging the error code directly (as there's no *good* alternative on iOS to that function).

It also includes a fix to the header search path for libssh2 which allows the library to be found properly when using a self-built copy of libssh2 (which places its headers in "libssh2/".

### CODE REVIEW

**Comment by carlosmn** [comment]
This removes any real error reporting as to why there was an issue, which would make it really hard to diagnose cert errors. It doesn't seem right that iOS would not provide any way to retrieve an error string due to a security error.

**Comment by ethomson** [comment]
Can you not just use a different mechanism on iOS to pull the data out of an `OSStatus`?  For example:  `GetMacOSStatusCommentString` or `GetMacOSStatusErrorString`?

**Comment by logancollins** [comment]
@ethomson Neither of those are available on iOS either. As far as I know, there is no public API to turn an OSStatus into a useful string on iOS.

**Comment by carlosmn** [comment]
That's terrible, but ok, if the best we can do there is some number...

As for the libssh2 change, its files are in the include path directly, and as you can see making it look for `libssh2/libssh2.h` breaks the build. If you have not installed libssh2 on the system but are relying on a version you've built, you need to tell the build system, via `CFLAGS` or a CMake option when you run CMake on the project.

**Comment by carlosmn** [comment]
I've cherry-picked the error-code change. The libssh2 includes are still a matter for the build system to tell cmake.

**Pull request closed without merging**
