### PR TITLE
config: Do not write repeated config section

### PR DESCRIPTION
**Pull request by linquize**
1. If the section already exist, new key should write to the end of that section
2. If there are multiple sections of same name, write to the last occurred section

### CODE REVIEW

**Comment by carlosmn** [comment]
The error that fails when applying the test changes to master is the one about preserving whitespace, which is not what this PR is about. This should have its own test, as it's a different kind of test from the ones we have. The existing tests test for functionality.

**Comment by carlosmn** [comment]
Why do you need a stack of positions in order to detect the latest section header? It should only be necessary to keep the last one.

There is a comment about a variable being a multivar which worries me. Whether a variable is a multivar or not depends *entirely* on the interpretation of that variable by the user of the configuration. The configuration parsing code cannot make this decision.

**Comment by ethomson** [comment]
I feel like the less impactful change here would be to simply buffer comments and write them in `write_on_eof` or `write_on_section` after writing the variable...

**Comment by carlosmn** [comment]
Since we operate on a line-by-line basis for writing variables (overwriting one or adding), if we're going to keep track of that stuff, IMO we should be keeping a list of lines, so we can refer to them later by index and we can keep track of two pieces of information, which line we want to affect, and whether we want to replace or append.

**Pull request closed without merging**
