### PR TITLE
config_file: Don't crash on options without a section

### PR DESCRIPTION
**Pull request by nelhage**
Found via fuzzing.

### CODE REVIEW

**Comment by ethomson** [comment]
Nice find - but git seems to parse configuration values without a section just fine.  I think that actually we should:

    if (current_section) {
        git_buf_puts(&buf, current_section);
        git_buf_putc(&buf, '.');
    }

    for (c = var_name; *c; c++)
        git_buf_putc(&buf, git__tolower(*c));

**Comment by ethomson** [comment]
I suspected it might be a warning with some commands.  (`git config —list` did not warn, but that was the extent of what I ran.)

Would you mind throwing a comment in that suggests that we should warn too?  Once warnings land we can wire it up.

Thanks!

**Comment by pks-t** [comment]
I'm not sure at all what happens in case we parse a config key without section. Could you please add a test that demonstrates that we do not fail at another place and that demonstrates what's expected to happen?

**Comment by pks-t** [comment]
Thanks for your fix and the test!

**Pull request merged**
