### PR TITLE
Explicitly handle GIT_DELTA_CONFLICTED in git_diff_merge()

### PR DESCRIPTION
**Pull request by swisspol**
(see commit message)

### CODE REVIEW

**Comment by swisspol** [comment]
Can someone restart the Travis build? Looking at the logs, seems like a CI problem.

**Comment by carlosmn** [comment]
What *was* happening before? Is there some test which covers this situation?

**Comment by swisspol** [comment]
Before it would create a hybrid `git_diff_delta` between the from and to ones, just because it wasn't special-cased like `GIT_DELTA_UNMODIFIED` or `GIT_DELTA_DELETED`. I'll see if I can put a test case together.

**Comment by swisspol** [comment]
Added unit test and rebased. The issue was actually bigger than I originally thought as a conflicted file in the index, but not existing in the workdir, could be reported as `ADDED` after merging the diffs (HEAD -> index -> workdir) instead of `CONFLICTED`.

**Pull request merged**
