### PR TITLE
Quick diff

### PR DESCRIPTION
**Pull request by Fallso**
Sped up diffing large work trees when using non-fnmatch pathspecs to see if the path we're analysing is part of a provided pathspec before recursion.

Rationale: On my system I had a folder with over 100,000 files in spread over 100s of folders - diffing and index status checks took forever. Now it doesn't!

### CODE REVIEW

**Comment by carlosmn** [comment]
There's a few lines of unrelated whitespace change, could you remove those?

**Comment by Fallso** [comment]
I noticed those in the diff but they didn't appear changed in my editor.
I'll check it out tomorrow in another editor

**Comment by Fallso** [comment]
I've removed the whitespace now

**Comment by ethomson** [comment]
Thanks for the pull request.  This is indeed unnecessarily slow in the current code and your change will help speed that up by avoiding unnecessary pathspec matching.

A still more advance option is #3402 - which *also* avoids iterating through entries that are not in the path list, which is a further win for machines with slow filesystems.

I'm closing this in favor of that, but thanks again.

**Comment by Fallso** [comment]
No problem, glad I could help!

**Pull request closed without merging**
