### PR TITLE
w32: fix unlinking of directory symlinks

### LINKED ISSUE #5147: Create repository has symlink left on Windows
### Reproduction steps
1. Windows 10 1809, enable developer mode so that symlink can be created without UAC elevation.
2. Install git for Windows 2.22 and enable symlinks during setup. Therefore `core.symlinks true`
3. Create a directory such as `C:\123`, this will be used as repository root.
4. Run following code
```C
git_repository *repo = NULL;
git_repository_init_options options = GIT_REPOSITORY_INIT_OPTIONS_INIT;
options.flags = GIT_REPOSITORY_INIT_MKPATH | GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE
git_repository_init_ext(&repo, "C:\\123", &options);
```

`.git` directory is created and initialized.
However, a temporary `.git2_abcdef` symlink is created in the working directory but not automatically deleted.

### Expected behavior
symlink automatically deleted by libgit2.

### Actual behavior
symlink not deleted.

### Version of libgit2 (release number or SHA1)
v0.28.0-232-ge50d138

### Operating system(s) tested
Windows 10 Pro 1809

### Cause
In repository.c `are_symlinks_supported()`,
1. Create a temp file `.git2_abcdef` where `abcdef` is random
2. Delete that temp file
3. Create a symlink `.git2_abcdef` that points to `testing`. However the file `testing` does not exist.
If target does not exist, `CreateSymbolicLinkW()` will create the symlink as directory type, even do not specify `SYMBOLIC_LINK_FLAG_DIRECTORY`
4. Check if `.git2_abcdef` is a symlink
5. Delete `.git2_abcdef` using `DeleteFileW()`. If symlink type becomes directory, `DeleteFileW()` does not work. Here is the problem why the symlink is left!!!

### Solutions
A. To test symlink, point to a file that exists, instead of that `testing`.
Create 2 temporary files, one is symlink that points to the other file. Then delete these 2 files.
B. Use `RemoveDirectoryW()` as fallback

### PR DESCRIPTION
**Pull request by pks-t**
This implements unlinking for directory symlinks on Win32. I've been annoyed by our misnamed "fileops.h" while at it and just renamed it to "futils.h", as it should be named. I hope this doesn't generate too many conflicts, otherwise I'll boot it out of this PR.

Supersedes #5149, fixes #5147

### CODE REVIEW

**Comment by pks-t** [comment]
I've force pushed fixes to more errors around symlink handling on Win32:

- When creating symlinks with a relative target, we didn't correctly determine the type of the target file as we checked for the target relative to the current directory instead of relative to the symlink directory. Such symlinks were then usually created as directory symlinks.
- When performing checkouts, we have to postpone handling of symlinks to the end. Otherwise, we may create symlinks to blobs which haven't yet been checked out, which would cause us to create the symlinks as directory symlinks instead of as file symlinks.

**Comment by ethomson** [comment]
Should we just skip the attribute check entirely, and try to delete the file, and if that fails, try to delete the directory?

**Comment by pks-t** [comment]
On Sat, Jul 20, 2019 at 03:19:36AM -0700, Edward Thomson wrote:
> Should we just skip the attribute check entirely, and try to
> delete the file, and if that fails, try to delete the
> directory?

I think we shouldn't. unlink(3P) doesn't ever unlink directories.
So if somebody called `unlink` on a non-symlink directory, then
we should fail. If we didn't perform the attribute check, then
we'd erroneously remove that directory.

**Comment by pks-t** [comment]
Rebased to fix conflicts

**Comment by ethomson** [comment]
> I think we shouldn't. unlink(3P) doesn't ever unlink directories.  So if somebody called `unlink` on a non-symlink directory, then we should fail. If we didn't perform the attribute check, then we'd erroneously remove that directory.

Aha, yes, that's very much true.  I was thinking that this was a unlink-symlink path, but obviously it's an unlink-whatever-was-passed-to-it function.

**Comment by ethomson** [comment]
Thanks!

**Pull request merged**
