### PR TITLE
Support non-cmake builds with an in-tree `experimental.h`

### PR DESCRIPTION
**Pull request by ethomson**
Provide an empty `include/git2/experimental.h` file for users who do not build with cmake. When building with cmake, we will generate the `experimental.h`, prefer it during builds, and install it with `cmake --target install`.

A different implementation to solve #6378

### CODE REVIEW

**Comment by ethomson** [comment]
Gah, no. Of course this doesn't work because `#include "experimental.h"` will prefer the one in the current directory. 🤔

**Comment by csware** [comment]
I think this will do the trick.

**Comment by ethomson** [comment]
There we go, we supplant the empty `experimental.h` with compile definitions. Rather gross, but should be effective. 😬

**Comment by ethomson** [comment]
Cool, thanks @csware!

**Pull request merged**
