### PR TITLE
ci: remove appveyor

### PR DESCRIPTION
**Pull request by ethomson**
Remove AppVeyor.  It's a fine provider, but unfortunately builds queue and complete very slowly and on top of that, I'm paying cash money for it.  After adding VSTS builds, they're not providing additional benefits to the PR or nightly build setup.

### CODE REVIEW

**Comment by ethomson** [comment]
(This PR is rather symbolic - I'll detach the AppVeyor configuration once we agree that this is good and right.)

**Comment by pks-t** [comment]
AppVeyor is horribly slow, and VSTS is a lot quicker even though it also builds Linux and macOS targets. So I'm all for removing AppVeyor

**Comment by tiennou** [comment]
FWIW, I'm 👍 too.

**Comment by ethomson** [comment]
🔥

**Pull request merged**
