### PR TITLE
Increase required version of cmake to 2.8

### PR DESCRIPTION
**Pull request by tkelman**
My bad, this policy line was introduced with #2986

### CODE REVIEW

**Comment by tkelman** [comment]
Now that there's a maint/v0.23 branch, this should also be backported to it.

**Comment by tkelman** [comment]
An alternative would be to bump `CMAKE_MINIMUM_REQUIRED` - there's a `cmake28` package for 2.8.11.2 in EPEL5, which is probably the only distribution old enough for this to matter.

**Comment by carlosmn** [comment]
I checked CentOS6 and Debian oldstable and both have 2.8 which is why I didn't merge this before the release. I'd be OK with bumping to 2.8 since it's available where we care. @ethomson ?

**Comment by tkelman** [comment]
I wound up having issues linking libgit2_clar with 2.6 anyway (wasn't listing libcrypto), ref https://github.com/staticfloat/ansible-julia_buildslave/pull/1

I think the anaconda folks also use centos 5 for building binaries for maximum compatibility with as old a glibc as anyone could conceivably be using, though they might be on 6 which we should probably switch to before it gets to be too painful.

**Comment by ethomson** [comment]
>  I'd be OK with bumping to 2.8 since it's available where we care.

Fine with me.

**Comment by tkelman** [comment]
>> I'd be OK with bumping to 2.8 since it's available where we care.
>
> Fine with me.

I know github doesn't send a notification, so just letting you know that I've replaced the PR content to do this instead.

**Comment by ethomson** [comment]
Looks good to me.  Thanks!

**Pull request merged**
