### PR TITLE
Added git_clone_into() API

### PR DESCRIPTION
**Pull request by swisspol**
Exposing this internal API is really needed if you want to be able to add submodules using libgit2. Otherwise, a lot of unnecessary code duplicating libgit2's internals is needed.

### CODE REVIEW

**Comment by carlosmn** [comment]
What can you do with this function that you can't with the repo creation callback in `git_clone()`?

**Comment by swisspol** [comment]
That's the first thing I tried. Check out the implementation of said callback in git_submodule_update(). It's actually handling a number of edge cases and using various SPIs.

**Comment by swisspol** [comment]
Actually looking into it, I remember better now: `submodule_repo_create()` is doing non-trivial things as you need to get the flags right and further more the other problem with git_clone() is that you can't even use it. It fails because the directory is not empty due to what the git submodule setup API does:
https://github.com/libgit2/libgit2/blob/72ca65d538d1e3ab7a9052613412bf121470dfd6/src/clone.c#L418

**Comment by swisspol** [comment]
The other thing I tried BTW was to use git_submodule_update() since it has built-in cloning code. But guess what, it fails if trying to use it on the result of git_submodule_add_setup() - I don't recall the exact error. So you can't use git_clone() and you can't use git_submodule_update() to "clone" the submodule!

After exposing the git_clone_into() API, you can now write reliable and easy to understand code to add a submodule.
- git_submodule_add_setup()
 - git_submodule_open()
 - git_remote_lookup()
 - git_clone_into()
- git_submodule_add_finalize()

As a matter of fact, I don't even use git_clone() anymore to do a clone, I use git_clone_into() as well:
- git_repository_init()
- git_remote_add()
- git_clone_into()

IMO it's cleaner and makes very clear what is happening, allows repo cloning and submodule initialization to  contrary to using the "black box" git_clone().

**Comment by carlosmn** [comment]
This is mixing a lot of different things. Are you having issues with adding submodules or with cloning in general? I don't get the complaint about having to implement a lot of the logic in libgit2 when you're asking libgit2 to perform less of it by using `git_clone_into()`.

`git_clone_into()` works sometimes, but it breaks completely if you have a custom transport and allowing the custom behaviours makes for combinatorial explosion of functions, which is why we removed it from the API in favour of the more general factory functions for the repository and remote.

**Comment by swisspol** [comment]
> This is mixing a lot of different things. Are you having issues with adding submodules or with cloning in general?

Different things but all closely connected :)

The first problem is that it's not possible AFAIK to actually do the clone step between git_submodule_add_setup() and git_submodule_add_finalize() with the current public APIs (unless you were to reimplement a lot of stuff that's already in libgit2). I encourage you to try to find a set of API calls that works as I couldn't :)

The second problem is that git_submodule_update() is essentially 2 APIs in 1:
- if the submodule is not initialized, it will initialize, clone and checkout (a la `git submodule update --init`)
- if the submodule is initialized, it will only attempt to move the HEAD to the target anything and not fetch anything (a la `git submodule update --no-fetch`)
While you would expect per its name and its behavior of being able to fetch/clone in one case to behave like `git submodule --update --init` all the time).

> I don't get the complaint about having to implement a lot of the logic in libgit2 when you're asking libgit2 to perform less of it by using git_clone_into().

I think libgit2 APIs need to strike the right balance between being too low-level and requiring clients to write a lot of potentially tricky glue code (that libgit2 might have internally anyway), and being too high-level and creating interoperability issues between the APIs themselves e.g. git_clone() and git_submodule_add_setup().

> git_clone_into() works sometimes, but it breaks completely if you have a custom transport [...]

I don't understand your point: git_clone() literally sets up the remote then calls clone_into(). If it works there, why wouldn't it work when called directly?

The alternative is to somehow modify git_clone() itself so it can work with git_submodule_update() but I wanted to do the simplest change first with this PR.

**Comment by swisspol** [comment]
Here's another issue with git_clone(): if passing a custom remote callback that simply returns an existing remote on disk, it will still attempt to call git_remote_save() on it. Not sure about side-effects of doing that.

**Comment by jamill** [comment]
> The first problem is that it's not possible AFAIK to actually do the clone step between git_submodule_add_setup() and git_submodule_add_finalize() with the current public APIs

When I looked at this, this was my conclusion as well. I don't think there is a way with the existing APIs to easily add a submodule to an existing repository. Are there scenarios where you want access to the functionality provided by `git_submodule_add_setup` and `git_submodule_add_finalize` that wouldn't be covered by a higher level function that encapsulates all these steps?

> The second problem is that git_submodule_update() is essentially 2 APIs in 1:

I envisioned this method to expose the "higher" level functionality of `git submodule update`. It optionally initializes a submodule. In my mind, it would be appropriate for this function to expose an option to fetch or not.

**Comment by swisspol** [comment]
>  Are there scenarios where you want access to the functionality provided by git_submodule_add_setup and git_submodule_add_finalize that wouldn't be covered by a higher level function that encapsulates all these steps?

I can't think of any right now. It could certainly be a single API. I also think the current approach of a pair of APIs is unique in libgit2 i.e. having APIs that do half a thing while all the others do complete actions if you see what I mean.

> I envisioned this method to expose the "higher" level functionality of git submodule update. It optionally initializes a submodule. In my mind, it would be appropriate for this function to expose an option to fetch or not.

I agree, this API should either not do any remote access at all and just the HEAD update part, or do all remote access as needed.

**Comment by carlosmn** [comment]
The `git_remote_save()` is a left-over from creating the remote in that function. I'd consider it a bug that we call it, though the existence of this function at all was a bad design decision back in the day.

As for the empty-dir check, that looks like it belongs either in the default repo creation callback or as an option. We should allow the caller to do whatever checks they want and allow cloning into something which is not empty at their own risk.

**Comment by carlosmn** [comment]
The save is on its way out in #3066 and I've just submitted a PR which tests the prescribed workflow for creating and cloning a submodule in #3115. It's not the most convenient method, so it's probably worth adding a convenience method to use the right clone callbacks.

**Comment by carlosmn** [comment]
At this time, `git_submodule_update()` does not use anything internal that I can see. There is a test to prevent regressions in being able to run `setup_add()` + `git_clone()` + `add_finalize()`. It looks like the complaints that originated this PR are solved.

**Comment by swisspol** [comment]
Thanks!

**Pull request closed without merging**
