### PR TITLE
refdb: Add an API git_refdb_get_backend

### PR DESCRIPTION
**Pull request by pmq20**

### CODE REVIEW

**Comment by ethomson** [comment]
Can you explain why this API would be useful?  If you're setting a custom refdb backend, I would expect you to keep a pointer to that, and not need to query it from libgit2...?

**Comment by pmq20** [comment]
@ethomson Thanks for reviewing. When implementing the `next` function of `git_reference_iterator`, we would love to get the backend-pointer out of `git_reference_iterator`'s `db` field.

**Comment by carlosmn** [comment]
if you're writing your own backend and iterator code, you're in control of which struct the iterator is backed by and can store whatever information you need there. If you need a pointer to the backend, you should store that pointer in your iterator struct, which all the iterator methods receive.

**Comment by ethomson** [comment]
I agree with @carlosmn - we would ask you to maintain this pointer yourself.  You should be able to simply create your `git_reference_iterator` as something like:

    struct my_custom_iterator {
        git_reference_iterator base;
        my_custom_refdb *refdb;
    }

And when you populate your custom iterator, you can put a link to your custom refdb.

**Pull request closed without merging**
