### PR TITLE
Allow git_diff_find_similar() to detect renames and copies of small files

### PR DESCRIPTION
**Pull request by swisspol**
See #2735 for the background discussion.

### CODE REVIEW

**Comment by swisspol** [comment]
Is this all good now?

**Comment by ethomson** [comment]
Sorry, I think one of my comments was sort of vague and actionless - I would really like to see us keep the test where we reject small files *without* `GIT_HASHSIG_ACCEPT_SMALL_FILES` in `test_diff_rename__handles_small_files`.  And add a new test that tests that renames are detected with `GIT_HASHSIG_ACCEPT_SMALL_FILES`.

Since I didn't communicate this well (or quickly) I'm happy to just take care of this post-0.22 if you are busy with other things.  Thanks!

**Comment by swisspol** [comment]
Note that there was no test actually testing that small files were rejected in libgit2. The previous test `test_diff_rename__handles_small_files()` was only testing that no `GIT_EBUFS` error was propagated to the caller. The test wasn't looking at the actual diff results to check that the small file changes weren't detected.

Furthermore, per my comments in the commits, `git_diff_find_similar()` sets the new flag `GIT_HASHSIG_ALLOW_SMALL_FILES ` by default, so you can't write tests that test both cases like you suggested.

**Comment by swisspol** [comment]
Unless you want me to add a new option to `git_diff_find_similar()` that enables `GIT_HASHSIG_ALLOW_SMALL_FILES` under the hood instead of having it ON by default? But I'm not sure why one would want that as there wouldn't be any performance impact by having it ON: it's doing the exact same computations as before but just not ignoring their result anymore.

If you need a refresher the background info for this PR is in #2735.

**Comment by ethomson** [comment]
Hmm.  I see.  Maybe I'm misremembering here - isn't `--find-copies-harder` required for this to work in git.git?  If so, why don't we just add a `GIT_DIFF_ALLOW_SMALL_RENAMES` or the like to turn this on?

**Comment by swisspol** [comment]
> isn't `--find-copies-harder` required for this to work in git.git

Yes but not for the reason you think.

Git does recognize rename of small files contrary to libgit2 (that's what my PR fixes).

However in the test case at http://stackoverflow.com/questions/27198414/git-status-git-diff-c-not-detecting-file-copy-in-index, passing `--find-copies-harder` is required so that Git looks for the right set of original files to compare the new ones against.

**Comment by ethomson** [comment]
I see.  Thanks for the clarification and your patient explanation.  Indeed you're right, of course, which can be seen experimentally:

```
% git diff -M01 HEAD
diff --git a/asdf b/fdsa
similarity index 44%
rename from asdf
rename to fdsa
index de98044..8e2cf81 100644
--- a/asdf
+++ b/fdsa
@@ -1,3 +1,3 @@
 a
-b
+z
 c
```

Obviously I cranked `-M` down low to make this work, but indeed git.git does not simply drop small files from consideration.  (Though they are unlikely to match the "very dissimilar" check at https://github.com/git/git/blob/master/diffcore-rename.c#L169.)

So I *think* what this small file check was intended to do was to avoid bothering to compare small files against large ones (similar to the aforementioned check in git.git) but to do it in a way that made sense of the layer of abstraction we have there.  (But I may be wrong.)

Two minor things that I want to think about a little bit more is the test at https://github.com/git/git/blob/master/diffcore-rename.c#L169 and ignoring zero-byte files (
http://thread.gmane.org/gmane.comp.version-control.git/193563/focus=193725 ) which would be a minor regression here.

Thanks again for pointing me in the right direction.

**Comment by swisspol** [comment]
If look at the comments in the hashsig implementation (prior to the PR) they mention it's because the hashing algorithm wouldn't work for small files. But perusing it, I don't see why it would be the case.

In any case, what's next here? Do you want to take this PR?

**Comment by ethomson** [comment]
Yeah, one of my concerns was that the size was an implementation detail, but I've also gone through this and don't believe that to be true.  Unless somebody steps in and corrects me, I will merge this once we have pushed 0.22 out the door fully.

Thanks again!

**Comment by ethomson** [comment]
Manually merged. Thanks again!

**Pull request closed without merging**
