### PR TITLE
Update chat resources in README.md

### PR DESCRIPTION
**Pull request by ddevault**

### CODE REVIEW

**Comment by pks-t** [comment]
@carlosmn: I haven't seen you in #libgit2 in a while. Would it be possible to either give me channel ops or to transfer ownership?

**Comment by ethomson** [comment]
I'm not there often but I'd like `+o` as well for redundancy if nothing else.

**Comment by pks-t** [comment]
> I'm not there often but I'd like +o as well for redundancy if nothing else.

Agreed, it's always best to have a high bus factor.

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
