### PR TITLE
winhttp: properly support ntlm and negotiate

### PR DESCRIPTION
**Pull request by ethomson**
When parsing unauthorized responses, properly parse headers looking for both NTLM and Negotiate challenges.  This was not previously necessary, since we did not previously need to set HTTP credentials.)

Set the HTTP credentials to default credentials (using a `NULL` username and password) with the schemes
supported by ourselves and the server.  It's not clear why this worked previously, but we now must explicitly call this API in order to authenticate with default credentials.

### CODE REVIEW

**Comment by ethomson** [comment]
Regrettably, we do not have unit tests that exercise default credentials.  I've thought about this in the past, but it's crazy hard to have Active Directory set up for testing.  Maybe nightlies, but with our CI infrastructure this is basically a non-starter.

**Comment by pks-t** [comment]
Huh. I always thought it would be nice if we had a separate CI system based on containers. Like that, we could easily spin up additional servers like LDAP, OpenSSH, proxies and other stuff. I know GitLab lets you do such stuff with their pipelines. Furthermore, that would also allow developers to easily spin up the same testing environment as it is inside of the CI system. We already had multiple occasions where we couldn't reproduce certain behaviour inside of the CI.

**Comment by ethomson** [comment]
Yeah.  I think that it would be hard to deal with AD/Kerberos in the context of containers, but I would be happy to be proved wrong.

**Comment by pks-t** [comment]
I was hoping that these features are also supported by slapd. Got no real idea though, only had the honor to set up testing LDAP systems twice.

**Pull request merged**
