### PR TITLE
Added git_stash_apply() and git_stash_pop() APIs

### PR DESCRIPTION
**Pull request by swisspol**
This is a tentative implementation of git_stash_apply() based on the actual Git implementation found at https://github.com/git/git/blob/master/git-stash.sh#L440.

Once you have git_stash_apply(), it's trivial to implement git_stash_pop() so I also added it.

### CODE REVIEW

**Comment by swisspol** [comment]
This implementation has full coverage and works great AFAIK. I also addressed most comments.

I wrote this implementation mirroring exactly what Git CLT implementation does, so it should be 100% compatible. If it were to be fully written "libgit2" style i.e. taking advantage of every inner API, the resulting code might be more obvious (and maybe, maybe, more compact, but I'm not sure), but then it would "diverge" from Git CLT. The problem is that the stash system in Git has a lot of intricacies and IMO the easiest to handle them correctly is to mirror the Git implementation, rather than trying to reverse engineer every corner case and rebuild it. As seen above with the discussions with @ethomson some changes suggested to have a "cleaner" implementation result in changes in the actual behavior.

Anyway, it's up to the maintainers to decide here :)

**Comment by ethomson** [comment]
> As seen above with the discussions with @ethomson some changes suggested to have a "cleaner" implementation result in changes in the actual behavior.

Hmm.  I don't see any behavioral changes...  all your tests passed with the code that I posted above.  Do you have some test that fails?

**Comment by swisspol** [comment]
> I don't see any behavioral changes

These were potential changes based on some earlier discussions which are gone from the history for some reason, but anyway it doesn't matter :)

> all your tests passed with the code that I posted above

Do you mean this code:
```
git_index *index;
git_repository_index(&index, repo);

git_oid current;
git_index_write_tree(&current, index);

git_tree *current_tree;
git_tree_lookup(&current_tree, repo, &current);

git_index *merged_index;
git_merge_trees(&merged_index, repo, NULL, untracked_tree, current_tree, NULL);

git_oid merged_tree_id;
git_index_write_tree_to(&merged_tree_id, merged_index, repo);

git_tree *merged_tree;
git_tree_lookup(&merged_tree, repo, &merged_tree_id);

options.checkout_strategy = GIT_CHECKOUT_SAFE | GIT_CHECKOUT_DONT_UPDATE_INDEX;

return git_checkout_index(repo, merged_index, &options);
```

You said "instead of taking the index tree or the unstashed tree that you previously created" so I assumed you wanted to do that instead.

In any case, what's next here? Do you want to grab the PR and modify it with your change? I'm not super comfortable with it in the sense that I'm not sure I 100% understand it.

**Comment by swisspol** [comment]
Closing per #3018

**Pull request closed without merging**
