### PR TITLE
Allow checkout to handle newly cloned repositories, remove `GIT_CHECKOUT_SAFE_CREATE`

### PR DESCRIPTION
**Pull request by ethomson**
The distinction between `GIT_CHECKOUT_SAFE` and `GIT_CHECKOUT_SAFE_CREATE` is very subtle and it is particularly easy assume that `SAFE_CREATE` should simply always be used, instead of as an edge case, since many peoples first interaction to checkout is through cloning a repository.  (We have even made that mistake within the library, as `d65ba24` and `c8e4040` illustrate.)

Our checkout implementation actually fails to handle the clone case correctly.  Git core behaves differently if an index is *empty* versus *nonexistent*, and we should here, too.  (Without this switch, we are unable to checkout repositories that were created by `git checkout --no-commit`, which is unfortunate.)

The first two commits here fix unnecessary uses of `SAFE_CREATE` within the library.  The second give checkout the semantics described above, where we implicitly enable `SAFE_CREATE` mode when there is no index file.

The final change is perhaps contentious.  Now that `SAFE_CREATE` is not necessary for clone, it becomes a very edge case concern.  (Though still useful as our checkout tests point out: our `testrepo` is checked in without files in the working directory.)  So we remove it from the list of strategies - if you want this behavior, now you have to specify it (`RECREATE_MISSING`) in addition to `SAFE`.

Certainly this final change is not necessary, but I think that it helps clarify and removes some of the confusion that we've seen with `SAFE_CREATE`.

### CODE REVIEW

**Comment by ethomson** [comment]
The last commit might be a bit reactionary since I found `SAFE_CREATE` confusing and have had to hear it from a bunch of other people who have, too.

/cc @arrbee

**Comment by carlosmn** [comment]
Regarding our tests which don't copy over the files, I wonder if the use of `SAFE_CREATE`/`RECREATE_MISSING` knows too much about how we handle this internally. Would we not get the same effect by checking out `"."` if it's in order to perform a setup rather than testing how we handle this case?

**Comment by jeffhostetler** [comment]
Is there a risk in recycling/re-purposing the GIT_CHECKOUT_ bits with apps that call into the lg2 dll without re-compiling (or is there enough other API breakage for that to not be a problem) ?

**Comment by ethomson** [comment]
> Regarding our tests which don't copy over the files, I wonder if the use of SAFE_CREATE/RECREATE_MISSING knows too much about how we handle this internally. Would we not get the same effect by checking out "." if it's in order to perform a setup rather than testing how we handle this case?

Surprisingly, it was quite a challenge to untangle the tests expectation that they could rely on `SAFE_CREATE`.  (Enough so that I gave up trying.)  I can take another shot if we feel it's particularly worthwhile.

Is your expectation that `SAFE_CREATE` / `RECREATE_MISSING` is enough of an edge case that it could be killed outright?

> Is there a risk in recycling/re-purposing the GIT_CHECKOUT_ bits with apps that call into the lg2 dll without re-compiling (or is there enough other API breakage for that to not be a problem) ?

I don't think there's risk here - without speaking about whether this is good or bad, at this point, we have so much gratuitous API breakage that ABI compat is not really a big concern.

**Comment by carlosmn** [comment]
>Is your expectation that SAFE_CREATE / RECREATE_MISSING is enough of an edge case that it could be killed outright?

From the description, it sounded to me like it was the particular way we/git handle the checking out when the index is missing. If that's the only situation, then it should be automatic promotion to this state, rather than something the user should care about.

It's fine if it's a lot of work to disentangle the tests from this expectations, we can leave that as future work.

**Comment by ethomson** [comment]
> From the description, it sounded to me like it was the particular way we/git handle the checking out when the index is missing. If that's the only situation, then it should be automatic promotion to this state, rather than something the user should care about.

So with these changes, this is something that we now do automatically promote to.  (If there's no `index`, we automatically turn on `RECREATE_MISSING` behavior.)

However, we still keep it as an option that a user *can* enable explicitly.  Our tests show why this might be useful - after banging around on this for a little while, it's actually a lot cleaner to simply start with a repository with an empty working directory (but an index) than to have a working directory and delete the items and `CHECKOUT_SAFE` or muck about with things so that `CHECKOUT_FORCE` really tests what we're trying to test.

I *did* clean up some tests that were specifying `RECREATE_MISSING` where they didn't need to, but I think the `checkout::index` tests *do* want this behavior.

Otherwise, I think this is ready to go and keeping the tests as-is is nicer than any changes that we could make.

**Pull request merged**
