### PR TITLE
Read prefix tests

### PR DESCRIPTION
**Pull request by pks-t**
Inspired by #4264. Along other tests, this also adds a test which segfaults due to the error fixed in the other PR.

### CODE REVIEW

**Comment by pks-t** [comment]
So this PR fails in the expected way. Rebasing it on top of the merged #4264

**Comment by ethomson** [comment]
Oh, huh.  I didn't realize that there was a possibility of a segfault there...  I just noticed that it bubbled up the error.

**Comment by pks-t** [comment]
Ah, small correction. I think the segfault is introduced by the tests themselves. It was caused by `read_prefix_1` returning an error and freeing the value, but also setting the out pointer. So when freeing the expected `NULL` value, we actually run into a double free.

**Comment by ethomson** [comment]
Ahhh - thank you, that does make sense.  :D

**Pull request merged**
