### PR TITLE
Nightlies: use `latest` docker images

### PR DESCRIPTION
**Pull request by ethomson**
I was originally trying to get the ppc64 builds working, but the emulator seems to not love emulating that platform.  I'm abandoning that but taking the update to use the `latest` images.

### CODE REVIEW

**Comment by ethomson** [comment]
I was seeing this before on the ppc64el builds where the gitdaemon tests appear to never finish.  I'll have to investigate this a bit to better understand what's happening.  😰

**Comment by pks-t** [comment]
Huh. Seems like Azure is confused :/

**Comment by pks-t** [comment]
Cool, thanks @ethomson :)

**Pull request merged**
