### PR TITLE
Add OpenSSL-FIPS option to USE_SHA256 CMake flag

### PR DESCRIPTION
**Pull request by marcind-dot**
Usage of the deprecated `SHA256_*` OpenSSL API in a FIPS compliant environment results in OpenSSL's assertion failure with the following description:
```
OpenSSL internal error, assertion failed: Low level API call to digest SHA256 forbidden in FIPS mode!
```

This PR adds a possibility to use the OpenSSL's `EVP_MD*` API instead of the deprecated `SHA256_*` API, by extending the optional CMake flag `USE_SHA256` with the new option called `OpenSSL-FIPS`. The new option is used to choose a hashing backend used by `libgit2` to calculate SHA256 hashes, in a similar way that currently existing options like `OpenSSL`, `OpenSSL-Dynamic`, `mbedTLS` etc do.

`OpenSSL-FIPS` is a fully opt-in option which is purposely not interfering with the existing options, because, after running some benchmarks, it's been discovered that using the `EVP_MD*` API causes hashing to be a bit slower in comparison to using the deprecated `SHA256_*` API.

Another change introduced in this PR is the enhancement of the Nightly workflow (`nightly.yml`) which will cause `libgit2` to be automatically built with `-DUSE_SHA256="OpenSSL-FIPS"` CMake flag, on Linux, macOS and Windows.

### CODE REVIEW

**Comment by ethomson** [comment]
Thanks for the PR 👀

**Comment by ethomson** [comment]
I made a few minor changes - I wanted to make sure that we supported FIPS mode on SHA1 as well, to ensure that we had more test coverage. Doing so actually unearthed a problem in the MIDX and commit graph code where we were finalizing the hash context and then trying to update it. For most of the hashes that's actually okay, but not for the new FIPS compliant hash.

**Comment by ethomson** [comment]
If you wouldn't mind taking a look at your leisure to make sure that everything makes sense. 🙏

**Comment by marcind-dot** [comment]
LGTM!

**Comment by ethomson** [comment]
Great; thanks again!

**Comment by lstoppa** [comment]
I have only one question about the change https://github.com/libgit2/libgit2/pull/6906/commits/a7ca589b43e7aefccbfe994c964c8ce0e262f5f3

In particular, the way you set `NULL`

```
	hash_cb_data.ctx = NULL;

	error = write_cb((char *)checksum, checksum_size, cb_data);
	if (error < 0)
		goto cleanup;
cleanup:
	git_array_clear(object_entries_array);
	git_vector_dispose(&object_entries);
	git_str_dispose(&packfile_names);
	git_str_dispose(&oid_lookup);
	git_str_dispose(&object_offsets);
	git_str_dispose(&object_large_offsets);
	git_hash_ctx_cleanup(&ctx);
	return error;
```

is there any reason why we don't do `hash_cb_data.ctx = NULL` inside the `cleanup` label? If "it doesn't matter" when we do it, maybe for consistency we should consider to move it there?

**Comment by ethomson** [comment]
It does matter; we need to clear it *before* the write callback. If it's null, the write callback will not try to calculate the hash, it will just do the write.

This is important in the final step, which is writing the calculated hash. We need to not try to add the hash itself to the calculate of the hash.

(In fact we've already finalized the hash context. In all the other hash implementations, it's okay to continue asking it to hash despite finalization, that's no longer true in the FIPS style routines.)

**Comment by lstoppa** [comment]
I see, thanks a lot for your explanation!

**Comment by ethomson** [comment]
Happily, it was a very good question that should have been better explained in the code, commit message, or PR.

**Pull request merged**
