### PR TITLE
C# userdiff patterns update

### PR DESCRIPTION
**Pull request by Therzok**
New keywords: foreach, break, in, try, finally, as, is, typeof, var,
default, fixed, checked, unchecked, this, lock, readonly, unsafe,
ref, out, base, null, delegate, continue.

Moved keywords to happen before modifier parsing, as matching a keyword
will stop modifiers from being matched.

The reasoning behind adding unsafe to keywords is being also a
statement that can happen inline in code to mention blocks which are
unsafe. Also, delegates are not necessarily declared in class bodies,
but can also happen inline in other functions.

Added parsing of events and delegates, which are like properties, but
take an extra keyword.

Added extern, abstract to methods modifiers.

Added abstract to properties/events/delegates.

Also, removed instanceof.

### CODE REVIEW

**Comment by ethomson** [comment]
I've added 

However, this is not emitting the diff output that I would have expected.  I'm seeing:

```
diff --git a/files/file.csharp b/files/file.csharp
index 1b17cb9..d0679ea 100644
--- a/files/file.csharp
+++ b/files/file.csharp
@@ -1,3 +1,2 @@
 using System;
-using System.Linq;

@@ -8,3 +7,3 @@ namespace Namespace.Some
        /// </summary>
-       public class Class
+       internal class Class
        {
@@ -15,3 +14,3 @@ private void TestUnchanged()
                // Scrub comment.
-               const int changed;
+               int changed;

@@ -20,3 +19,3 @@ async void TestFunction()
                        // Padding.
-                       int changeme;
+                       int changed;
                }
@@ -27,3 +26,3 @@ async void TestFunction()
                        {
-                               return 0;
+                               return 1;
                        }
```

Hunk 1 looks correct.  Hunk 2 I would have expected to be attributed to `internal class Class`.  Hunk 3 looks correct also, but Hunk 4 I would have expected to be attributed to `static readonly int SomeProperty`...

**Comment by ethomson** [comment]
See the last commit on https://github.com/ethomson/libgit2/compare/pr_2774?expand=1

**Comment by Therzok** [comment]
Ok, property regex needs fixing. The class thing is a diff driver issue,  not an userdiff pattern. Check c++ equivalent? I think it happens the same way.

But yeah, I'll recheck the property. Thanks! :D

**Comment by ethomson** [comment]
Oh!  Okay.  Sorry, I don't really know much about the diff drivers, I just splatted out what I would have expected as a user.  :)

**Comment by Therzok** [comment]
Well, I would've expected the namespace to be shown. The diff hunk header tells you which block you're in. Whether you're in a function definition, or a class, or anything else. In short, it should take the  containing declaration.

**Comment by ethomson** [comment]
@Therzok I realize that this is a bit old, and probably not on the top of your todo list, but do you have a moment to fix this up so that we can get it merged?  Thanks!

**Comment by ethomson** [comment]
FYI: we're trying to clean up some of the dead pull requests that haven't had any activity for a while.  I'm going to close this in seven days (May 4) unless there is some activity.  Thanks!

**Comment by Therzok** [comment]
I'll make sure the progress doesn't go to waste. Just don't delete your branch and I'll reopen a PR with all these things. :D

**Comment by ethomson** [comment]
Closing due to inactivity.

**Pull request closed without merging**
