### PR TITLE
 cmake --build .. instead of  cmake --build .

### PR DESCRIPTION
**Pull request by swuecho**
two dot

### CODE REVIEW

**Comment by ethomson** [comment]
I think that the original documentation is correct.  Are you having trouble?

**Comment by swuecho** [comment]
$ mkdir build && cd build
$ cmake ..
$ cmake --build .

after cmake .., still in build dir

**Comment by tiennou** [comment]
Results here :

```
$ mkdir build && cd build
$ cmake ..
[output]
$ cmake --build ..
Error: could not load cache
```

**Comment by swuecho** [comment]
```
➜  build cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hwu/Download/libgit2-0.26.0
➜  build cmake --build .
Error: could not load cache
➜  build cmake --build ..
[ 21%] Built target git2
[100%] Built target libgit2_clar
```

probably does not matter. should be easy for anyone to figure out.

**Comment by tiennou** [comment]
You might have run `cmake` from the root of the source tree once, hence there's a `CMakeCache.txt` file & `CMakeFiles` directory and running `cmake --build ..` from `build` finds that ?

**Comment by ethomson** [comment]
Yes, that's a good suggestion - if you ever run `cmake` from the source tree's root, `cmake` will try to re-update those files, instead of in the new place.

Curious if you have the same behavior in a fresh clone?  (Or something where you've `git clean`ed everything.)

**Pull request closed without merging**
