### PR TITLE
Added git_diff_index_to_index()

### PR DESCRIPTION
**Pull request by swisspol**

### CODE REVIEW

**Comment by swisspol** [comment]
Before spending time adding a unit test, I wanted to pre-fly this PR and see if it's OK to have in libgit2 in the first place.

I use this API in http://gitup.co when doing advanced commit manipulation: this allows to manipulate the commit contents "in-memory" without checking it out on disk, when then requires diffing the index use to hold the modified commit against another index in some cases.

**Comment by ethomson** [comment]
>  I wanted to pre-fly this PR and see if it's OK to have in libgit2 in the first place.

Definitely!

**Comment by swisspol** [comment]
Unit test added!

**Comment by nulltoken** [comment]
Same build error than  #3276. Restarted as well.

/cc @carlosmn

**Comment by swisspol** [comment]
All right, build is passing. Can this PR be landed? :smile:

**Comment by carlosmn** [comment]
We can look at merging it after we unfreeze master.

**Pull request merged**
