### PR TITLE
Allow merges of files (and trees) with whitespace problems/fixes

### PR DESCRIPTION
**Pull request by jacquesg**
I often find merging with ```git merge -s recursive -X ignore-all-space branch_to_be_merged``` to be quite useful, especially when fixing existing formatting problem and adding new features in a code base.

This PR exposes the ability to turn these options on. CC @ethomson, this is your area of expertise IIRC. I'm not quite sold on where and how I had to add the flags...

### CODE REVIEW

**Comment by jacquesg** [comment]
I've also added options to enable the patience and minimal diff algorithms. Had a real world example of a merge incorrectly succeeding today (when not using the patience algorithm).

**Comment by jacquesg** [comment]
Any review comments here? @ethomson

**Comment by ethomson** [comment]
Looks good to me, I can see where this would be very useful.

Would you mind filling out the `CHANGELOG` to describe this?  Especially since this is a bit breaking for source compat in the `flags` -> `tree_flags`.

**Comment by jacquesg** [comment]
Yes, I was definitely going to do that, was just waiting to see if there was any feedback :)

**Comment by ethomson** [comment]
:+1:

**Comment by jacquesg** [comment]
Done.

**Comment by jacquesg** [comment]
Should be good to merge.

**Comment by jacquesg** [comment]
@ethomson Can we please get this one merged? I've got a blocking issue in the perl bindings I need to complete ASAP.

**Comment by jacquesg** [comment]
Awesome, thanks!

**Pull request merged**
