### PR TITLE
Created clar test to create 4GB+1 byte file.

### PR DESCRIPTION
**Pull request by jeffhostetler**
Recreate pull request #3121 using master as a baseline.

This commit adds a test to create, stage, and commit a huge file.

### CODE REVIEW

**Comment by carlosmn** [comment]
Cool. Can we not name functions with leading underscores? We can just have static functions with normal names.

**Comment by jeffhostetler** [comment]
Sorry, old habit.  Fixed.

**Comment by carlosmn** [comment]
As a sanity check, I think we should check that we get back the expected id for the blob, as otherwise we won't be able to detect if we broke reading past `SIZE_MAX`.

**Comment by jeffhostetler** [comment]
Yeah, I was wondering about how far to take this test, given that huge files are a bit of an edge case. When I started it was just additional testing for #2936 and #2932.  I could see adding a bunch of asserts WRT id's and checkouts.  I was also wondering about another test case using data that won't compress since it looks like 4Gb+1 zeroes compresses to about 18Mb. And maybe one using write() rather than ftruncate() so that mingw32 won't have to be skipped.

I'll look into adding something along these lines.
Thanks

**Comment by carlosmn** [comment]
The main reason for asking for an id check is to answer the question "are we actually putting the whole blob into the odb?" We cannot currently *extract* this object where a 4GB+1-sized file would cause an issue so we would expect that to return OOM (though I suppose we might test that, maybe).

As for the mingw32 issue, it occurs to me that we don't need to have the file exist at all. You can use `git_blob_create_fromchunks()` to insert as many gigs into the odb as you want. Though to be honest, it's essentially equivalent to using `write()`, it's just that it's the library doing it for you.

**Comment by jeffhostetler** [comment]
Closing this in favor of #3197.

**Pull request closed without merging**
