### PR TITLE
Support http cookie file

### PR DESCRIPTION
**Pull request by ankurmittal**
This patch supports passing http cookiefile when libcurl is present
#3397

### CODE REVIEW

**Comment by ankurmittal** [comment]
+@petrhosek

**Comment by ankurmittal** [comment]
#3397

**Comment by ethomson** [comment]
Thanks for tackling this!

I think that if this is something that we're going to include then this is probably not something that we want to include at the TLS transport level, but when we build requests.  I realize that OpenSSL has the concept of a cookie file but this doesn't match the abstraction that we've built.

Instead, cookies should be considered part of the request itself, not part of the cryptographic or connection layer.  This means that we can probably add cookie code to `transports/http.c` (perhaps in `gen_request`?) and `transports/winhttp.c` (maybe in `do_send_request`?) - which means that we add it in two places instead of however many TLS backends there are.

This means reading the `http.cookieFile` and applying them ourselves, but this seems much more robust than only adding it for a single backend.

**Comment by ankurmittal** [comment]
Don't have a windows machine, so did not add support for it as no way to test

**Comment by ankurmittal** [comment]
Also not sure about license, should I copy license from other files into cookie.cc and cookie.h?

**Comment by ankurmittal** [comment]
Please review

**Comment by ethomson** [comment]
Hi @ankurmittal - I didn't see that you had moved this into `gen_request` - thanks for that, I'll try to take a look at this soon.

**Comment by ankurmittal** [comment]
rebased the changes with latest

**Comment by ankurmittal** [comment]
please review, also build failure is not because of this CL, it is already failing in master

**Comment by petrhosek** [comment]
@ethomson Would it be possible to review and merge this pull request? We need the support for cookies in order to use libgit2 in our setup.

**Comment by ankurmittal** [comment]
Hi, Can someone please review it?

**Comment by pks-t** [comment]
Hi @ankurmittal. Thanks for your PR. Unfortunately, I'm a bit on the edge about it, and we actually had a rather long discussion yesterday on how to handle things like cookie files for our transports.

So the biggest problem I see here is that we actually include a large amount of non-trivial code from a different project into ours, leaving us with the burden to maintain it, fix issues and triage security issues. Unfortunately, this is not something I am personally keen on doing, which is why I am opposed to including the cookie code from libcurl.

So as mentioned, we had a lengthy discussion on how to proceed from here, because such "high-level" features like for example cookie files or SSL certificates, which users of our library assume to just work, are currently not handled by our transports, and we actually want them to stay dumb. But as these kinds of requests pop up quite frequently, we thought about adding an additional transport which "just works" as expected. It would automatically handle encryption, certificates and also cookie files without us getting in the way by simply offloading all this to libcurl. So while this backend would be rather restricted in advanced use cases, it would be simple to use for other scenarios.

So this is not something that exists yet and is currently only in a drafting stage. Furthermore, this transport will probably not be developed as part of core libgit2 but rather in an external repository like "libgit2/libgit2-curl-transport".

**Comment by garymm** [comment]
@pks-t is there an issue tracking the work you described? If not, can you please open one and reference it here?

**Comment by ethomson** [comment]
As mentioned, `http.cookiefile` support is a reasonable request, but this isn't the way we'd like to proceed with this.

**Pull request closed without merging**
