### PR TITLE
typos in comments

### PR DESCRIPTION
**Pull request by olshevskiy87**

### CODE REVIEW

**Comment by whoisj** [comment]
:+1: and wow, none of them are my spelling mistakes :open_mouth:

**Comment by carlosmn** [comment]
The code under `deps/` is not ours so we should not change it at all as it would just make it harder to merge any updates we might do.

**Comment by whoisj** [comment]
> the code under deps/ is not ours 

ahh yeah, glad you're paying attention. I was only looking at the spelling mistakes / fixes -- not the paths. :hushed: Nice catch.

**Comment by olshevskiy87** [comment]
oh.. if it's not yours, then I'm sorry )

**Comment by carlosmn** [comment]
There are three changes or so which do change our code; if you undo the changes to `deps/` and squash, we could merge that.

**Comment by olshevskiy87** [comment]
> if you undo the changes to deps/ and squash

ok. done

**Pull request merged**
