### PR TITLE
Set up git_trace in clar test suite.

### PR DESCRIPTION
**Pull request by jeffhostetler**
This code provides a way for the CLAR test runner to optionally git_trace() before running a test.  This has proven useful when adding tracing inside libgit2 routines during development.

Currently, it always assume TRACE level.

Currently, I have just the basic printf() callback on all platforms.  Windows users can also request a "printf() + debugger console" callback.

It would be easy to extend this to have a callback to write the trace log to a file instead.

### CODE REVIEW

**Comment by carlosmn** [comment]
This changes `tests/clar.c` which comes from clar itself, so we shouldn't be changing it in the library, as it shouldn't know about libgit2 directly, and an update might just undo this change.

Could we put the call to `cl_maybe_enable_trace()` in `main.c` between setting up the library and starting the test suite proper?

**Comment by jeffhostetler** [comment]
sure. i'll take a look.  i completely forgot that clar itself is imported.  thanks.

**Comment by jeffhostetler** [comment]
OK I've moved the global trace setup into main.c rather than clar.c.  (And did a little house keeping.)

This version is not quite as nice because there isn't an easy way to globally log the beginning/ending of each test.  It looks like there are recent verbose changes in the upstream clar, so I'll try to submit a PR for that up there.

**Comment by carlosmn** [comment]
Adding hooks for that would be pretty cool. Would you prefer holding off on merging this until you can update clar with those hooks? Or would you rather see this part get to master earlier?

**Comment by jeffhostetler** [comment]
yeah, let's wait on this. adding a hook to clar itself makes me also want to expand what i have here.

**Comment by jeffhostetler** [comment]
I just created https://github.com/vmg/clar/pull/67 with the CLAR-specific global trace changes.

The code in this PR won't compile until those changes are pulled into libgit2.

**Comment by jeffhostetler** [comment]
These changes cause CLAR to emit git_trace() messages before, during, and after each test. Any trace messages issued by the test itself appear between these markers.  We also print the execution time of the run() itself and of the whole init-run-cleanup sequence for each test.

 We also get delimiters to note each suite.


```
S:\libgit2\build>.\Debug\libgit2_clar.exe -sperf::merge
Loaded 281 suites:
Started


================================================================
perf::merge: Begin Suite

perf::merge::m1: Begin Test
perf::merge::m1: Begin Run
m1:      clone:     17.541
m1:   checkout:      3.262
m1:      merge:      6.355
perf::merge::m1: End Run
perf::merge::m1: End Test (27.276 27.278)
.
perf::merge::m2: Begin Test
perf::merge::m2: Begin Run
m2:      clone:     17.843
m2:   checkout:      3.271
m2 C:/jh/temp/libgit2_tests_a03100/m2/:
                    :   MergeB2A,    Reset2A,  CheckoutB,   MergeA2B,    Reset2B,  CheckoutA,
             m2[  0]:      6.457,      2.774,      3.559,      1.984,      1.297,      2.244,
             m2[  1]:      5.224,      2.401,      3.293,      2.124,      0.763,      2.558,
             m2[  2]:      4.721,      2.810,      3.056,      1.762,      0.426,      1.979,
             m2[sum]:     16.403,      7.985,      9.908,      5.871,      2.487,      6.781,
perf::merge::m2: End Run
perf::merge::m2: End Test (71.451 71.453)
.

perf::merge: End Suite
================================================================
```

**Comment by carlosmn** [comment]
For unix, you use `gettimeofday()` to get the elapsed time, but that's something one should only use as a last resort, as it's not necessarily all that accurate and can vary quite a bit if the system is trying to fix some innacuracy it noticed with NTP.

We have `git__timer()` available in `src/util.h` which already tries to use monotonic clocks where available, which should be more accurate at least on unix. I'm not too familiar with `QueryPerformanceCounter()` vs `GetTickCount()`. Does the former look up the CPU bookkeeping register?

**Comment by jeffhostetler** [comment]
Not sure.  For the tests runs on my huge repo, I was trying to lop minutes off the times of a merge and etc., so I wasn't really worried about high-precision timers.  Let me take a look.

**Comment by jeffhostetler** [comment]
OK. I went ahead and substituted in calls to git__timer() instead of the platform code that I had.  Seems to work fine on my WIndows machine.

**Comment by carlosmn** [comment]
Moving away from `gettimeofday()` isn't so much about getting the last microsecond out, but that the wall-clock value can jump forwards and backwards at arbitrary times by arbitrary amounts, and we already have the code to handle this, so we might as well. If we do need more accuracy at some point we can revisit the clock source.

**Comment by jeffhostetler** [comment]
Agreed.  Hadn't thought about the wallclock jumping.  Thanks.   And agreed, I'm not worried about hi-res either.

**Pull request merged**
