### PR TITLE
transports: Avoid walking over non-commit objects

### LINKED ISSUE #3595: libgit2 assumes everything not under refs/tags are commits
In my application that uses `libgit2` I create tags to blobs (which is unusual because tags normally point to commit objects) and create symbolic references to those tags under `refs/snapshots`. The `git` program has no problems fetching those references:

```
10:37 $ git fetch origin refs/snapshots/*:refs/snapshots/*
remote: Counting objects: 2, done
remote: Finding sources: 100% (2/2)
remote: Total 2 (delta 0), reused 2 (delta 0)
Unpacking objects: 100% (2/2), done.
From ssh://gerrit.qnective.com:29418/qtalk_proj
 * [new ref]         refs/snapshots/bc1b0ddb-37b8-44b3-9589-9e31bf17c95b -> refs/snapshots/bc1b0ddb-37b8-44b3-9589-9e31bf17c95b
```

But `libgit2` fails with "Object is not a committish". In `smart_protocol.c`, function `fetch_setup_walk` we can see a call to `git_revwalk_push`, which will assume the reference must be a commit, which is not always the case.

### PR DESCRIPTION
**Pull request by biodranik**
The updated version of stalled #4383. The issue is still there for many years and needs to be fixed.

References may point to objects that are not commits, such as tags to
blobs. In that case, the reference must not be walked over further.

Fixes #3595.

### CODE REVIEW

**Comment by ethomson** [comment]
This looks like a straight reopening of the other PR, is that correct?

The other PR has outstanding comments that need to be addressed: https://github.com/libgit2/libgit2/pull/4383#issuecomment-340208211

**Comment by ethomson** [comment]
(Thanks for taking over this pull request, by the way.  It would indeed be nice to have this fixed.  🙇 )

**Comment by biodranik** [comment]
@ethomson I have rebased the PR and fixed minor formatting issues. Unfortunately, I don't know libgit2 sources to implement what is recommended in the [comment](https://github.com/libgit2/libgit2/pull/4383#issuecomment-340208211) by @carlosmn. May be someone else can help?
For now, this issue blocks libgit2 support for some real-world cases, and it would be great to have a fix as soon as possible.

**Comment by ethomson** [comment]
@carlosmn can you help @biodranik make the changes that you suggested so that we can land this?

**Comment by tiennou** [comment]
I've opened #5195, which is the change proposed by @carlosmn. Sorry for the (hopefully friendly) take-over @biodranik, and thanks for writing the test case. If you can give a spin to this version with your repository, that would be nice, and if it looks like I missed something, ping me.

**Comment by ethomson** [comment]
Closed in favor of #5195

**Pull request closed without merging**
