### PR TITLE
Handle hide-then-push in the revwalk

### PR DESCRIPTION
**Pull request by carlosmn**
When a commit is first set as unintersting and then pushed, we must take care that we do not put it into the commit list as that makes us return at least that commit (but maybe more) as we've inserted it into the list because we have the assumption that we want anything in the commit list.

This fixes the aside made in #3034 though it shouldn't be the cause of the slowness.

### CODE REVIEW

**Comment by ethomson** [comment]
Interesting...  I must admit that the current behavior seems more intuitive.  Right now if I push then hide the same commit, it stays hidden.  If I hide then push the same commit, it stays pushed.  With this change you can never unhide a commit, is that right?

Do I understand correctly that #3034 could be solved simply by pushing then hiding?

(I realize that this is not a particularly common thing, so maybe it doesn't matter.  But if we're going to do this, I think we should update the docs.)

**Comment by carlosmn** [comment]
If we want to implement something like what rev-list does, then the order should not matter. Once you've ignored a commit, you cannot unignore it.

I'm not sure which docs would need updating. The docs for `_push()` just say that we'll set the given commit as one of the roots to start at, we don't promise you'll get it back on the output. `_hide()` already tells you that it will hide the given commit, so for me this brings it in line with the docs, as we don't say that it can be undone. Maybe it's too subtle...

Maybe the name `_push()` suggests too much that you might be pushing some data on to a stack. What it really comes down to is setting the set of positive and negative references (or commits in our case) which do not have any ordering between them.

**Comment by carlosmn** [comment]
I've reworded the `_push()` docs so it's hopefully clearer what we mean by pushing and hiding.

**Comment by ethomson** [comment]
A gentleman you are!

**Pull request merged**
