### PR TITLE
deps: ntlmclient: fix htonll for Haiku

### PR DESCRIPTION
**Pull request by mmuman**
Use B_HOST_TO_BENDIAN_INT64 for that.

### CODE REVIEW

**Review by pks-t — APPROVED** [review]
Thanks, your changes look good to me. We'll still need to fix macOS 10.9, but that definitely doesn't need to be part of this PR. @ethomson, want to have another look?

**Comment by pks-t** [comment]
Maybe we should just use the generic version I've posted at #5614. There's just too many platforms and it's not like this code is performance critical in any way, so providing a generic platform feels a lot saner to me.

**Comment by ethomson** [comment]
I'm going to merge this as-is while we sort out how to provide a more generic version in #5614

**Comment by ethomson** [comment]
Thanks @mmuman!

**Comment by mmuman** [comment]
:-)

**Pull request merged**
