### PR TITLE
reflogs: fix behaviour around reflogs with newlines

### PR DESCRIPTION
**Pull request by pks-t**
This pull request has been inspired by #5266 and aims to fix two things:

1. We fail to parse corrupted reflogs, which git is reading just fine.
2. We corrupt the reflog if somebody calls `git_stash_save` with a commit message containing newlines, as we print the newlines verbosely into the stash's reflog.

This pull request fixes both issues. It makins our parser more lenient with regards to broken lines in the reflog. Last, it will sanitize reflog messages to not contain any newlines anymore. While we previously rejected such messages in one location, we didn't at another place in libgit2 (refdb_fs). And as git just replaces newlines with spaces, I've modified both places to accept reflog messages with newlines, but replace them with spaces now.

### CODE REVIEW

**Comment by lolgear** [comment]
@pks-t Looks nice!
I would like to discuss another approach on which I am working.

Consider enumeration 

```c
typedef enum git_reflog_component {
	git_reflog_component_init, // init entry.
	git_reflog_component_oid_old, // length > 0 && length <= OIDSIZE (20) && is_hex(character)
	git_reflog_component_oid_cur, // length > 0 && length <= OIDSIZE (20) && is_hex(character)
	git_reflog_component_commiter, // length > 0 && contains(name) && contains(email) && contains(time)
	git_reflog_component_msg, // length >= 0 && last_at_('\n')
	git_reflog_component_finalize, // finalize. Put entry into array.
} git_reflog_component;
```

Or simpler

```c
typedef enum parsing_step {
	init,
	oid_old,
	oid_cur,
	commiter,
	msg,
	finalize,
};
```

And how it could be used.

```c
component = git_reflog_component_init;

while(buf_size > GIT_REFLOG_SIZE_MIN) {
  switch (component) {
    case git_reflog_component_init: {
      entry = git__calloc(1, sizeof(git_reflog_entry));
      GIT_ERROR_CHECK_ALLOC(entry);

      entry->committer = git__calloc(1, sizeof(git_signature));
      GIT_ERROR_CHECK_ALLOC(entry->committer);
      component = git_reflog_component_oid_old;
      break;
    }
    case git_reflog_component_oid_old: {
      if (git_oid_fromstrn(&entry->oid_old, buf, GIT_OID_HEXSZ) < 0) {
        // error occurred.
        // we should reset cycle.
        // and also we don't need to change component.
        // cleanup.
        invalid_character_position = git_oid_find_invalid_charater_position_at_strn(buf, GIT_OID_HEXSZ);
        if (invalid_character_position < 0) { // error occurred, so, cleanup and leave.
          error_occurred = -1;
        }
        else { // invalid character, seek to position following invalid character and try to get oid again.
          git_reflog_entry__free(entry);
          valid_character_position = 1 + invalid_character_position;
          seek_forward_new(valid_character_position);
          component = git_reflog_component_init;
        }
      }
      else {
        seek_forward_new(GIT_OID_HEXSZ + 1);
        component = git_reflog_component_oid_cur;
      }
      break;
    }
    case git_reflog_component_oid_cur: {
      if (git_oid_fromstrn(&entry->oid_cur, buf, GIT_OID_HEXSZ) < 0) {
        // error occurred.
        // we should reset cycle.
        // and also we don't need to change component.
        error_occurred = -1;
        // invalid_character_position = git_oid_find_invalid_charater_position_at_strn(buf, GIT_OID_HEXSZ);
        // if (invalid_character_position < 0) { // error occurred, so, cleanup and leave.
        //  error_occurred = -1;
        // }
        // else { // invalid character, seek to position following invalid character and try to get oid again.
        //  valid_character_position = 1 + invalid_character_position;
        //  seek_forward_new(valid_character_position);
        // }
      }
      else {
        seek_forward_new(GIT_OID_HEXSZ + 1);
        component = git_reflog_component_commiter;
      }
      break;
    }
    case git_reflog_component_commiter: {
      ptr = buf;
      /* Seek forward to the end of the signature. */
      while (*buf && *buf != '\t' && *buf != '\n')
        seek_forward_new(1);
      if (git_signature__parse(entry->committer, &ptr, buf + 1, NULL, *buf) < 0) {
        error_occurred = -1;
      }
      else {
        component = git_reflog_component_msg;
      }
      break;
    }
    case git_reflog_component_msg: {
      if (*buf == '\t') {
        /* We got a message. Read everything till we reach LF. */
        seek_forward_new(1);
        ptr = buf;

        while (*buf && *buf != '\n') seek_forward_new(1);

        entry->msg = git__strndup(ptr, buf - ptr);
        GIT_ERROR_CHECK_ALLOC(entry->msg);
      } else
        entry->msg = NULL;
      while (*buf && *buf == '\n' && buf_size > 1) seek_forward_new(1);
      component = git_reflog_component_finalize;
      break;
    }
    case git_reflog_component_finalize: {
      if (git_vector_insert(&log->entries, entry) < 0) {
        error_occurred = -1;
      }
      else {
        component = git_reflog_component_init;
      }
      break;
    }
  }
  if (error_occurred < 0) {
    break;
  }
}
```

What do you think about this approach in parsing?

**Comment by pks-t** [comment]
I thought about doing that, too. I've converted the patch parser to use the exact same mechanism via a state machine. For this case here I didn't deem it worthwhile enough, as there is not a lot of variance. I'd propose the following: let's merge the conversion to `git_parse_ctx`, which was my longterm goal when I first introduced the parsing interface, to provide a common parsing interface for all of our code and thus reduce duplication. I'd still love to see the conversion to use a state machine with the then-converted code after the merge, just to see whether it makes sense for such a linear parser. Are you fine with that?

**Comment by lolgear** [comment]
@pks-t Yes, nice decision :)
I can't wait to see this PR is merged :)

By the way, how do you run tests and debug them? In Mac I use only terminal and sublime text. This approach I don't appreciate, cause I need to 'printf'ying every step. Yes, it is old school, but I need to inspect every structure to know what I should output to console. Not too much convenient at first commits in big C project.

**Comment by pks-t** [comment]
On Sun, Oct 20, 2019 at 02:02:17AM -0700, Dmitry Lobanov wrote:
> @pks-t Yes, nice decision :)
> I can't wait to see this PR is merged :)

Cool, thanks!

> By the way, how do you run tests and debug them? In Mac I use
> only terminal and sublime text. This approach I don't
> appreciate, cause I need to 'printf'ying every step. Yes, it is
> old school, but I need to inspect every structure to know what
> I should output to console. Not too much convenient at first
> commits in big C project.

My toolset includes vim and gdb, only, so it probably is not too
comfortable either. It works just fine for me and forces me to
understand the codebase better, though, due to the lack of code
completion and stuff like that. While possible to implement in
vim, I've noticed that my understanding of the code base grows if
I have to manually look up functions I want to use instead of
just relying on function names.

On some occasions, I also use valgrind to debug memory errors,
but I have to start into a virtual machine to use that. I didn't
yet have any luck to get it to cleanly compile and run on my
musl libc-based system.

**Comment by tiennou** [comment]
@lolgear I've filed #5278, which is all my "private" developer stuff. There's a build.sh script that should setup an appropriate .xcodeproj, though you may have to fiddle with your brewed paths. Thanks for asking 😉, HTH !

**Comment by tiennou** [comment]
(I'm like, still 😮 and 😨 at your choice of workflow @pks-t, but I don't intend to change my reviews in any way 🤣🙏.)

**Comment by pks-t** [comment]
> but I don't intend to change my reviews in any way

And neither should you. With an increasing diversity of people and different toolsets, it is more likely that we catch different types of bugs. And in the end, I'm happy to receive reviews in the first place ;)

**Comment by lolgear** [comment]
@pks-t Is it possible to ask for review and merge this PR as soon as possible? It fixes a blocking issue...

**Comment by ethomson** [comment]
Thanks, @pks-t.  That was an enjoyable read.

**Comment by pks-t** [comment]
Thanks @ethomson!

**Pull request merged**
