### PR TITLE
Headers cleanup

### PR DESCRIPTION
**Pull request by anatol**
A small cleanup for libgit2 headers

### CODE REVIEW

**Comment by ethomson** [comment]
Oops, good catch on `email_from_diff`. It was actually supposed to be in the `sys/email.h` header. Would you mind zapping it from `email.h` instead? 🙏

**Comment by anatol** [comment]
> Oops, good catch on `email_from_diff`. It was actually supposed to be in the `sys/email.h` header. Would you mind zapping it from `email.h` instead? 🙏

Sure, done. It turns there are some users that expect the function to be at `git2/mail.h`, so I fixed them as well.

**Comment by ethomson** [comment]
Awesome, thanks! 🙏

**Comment by anatol** [comment]
@ethomson could you please approve the github workflow to see if my last patch fixes the compilation issue?

**Comment by ethomson** [comment]
Thanks!

**Pull request merged**
