### PR TITLE
patch: minor documentation fix.

### PR DESCRIPTION
**Pull request by vivaladav**
Fix @return description of git_patch_num_lines_in_hunk.

Issue #3965

### CODE REVIEW

**Comment by staticfloat** [comment]
As a gentle reminder, please try to quote any macro names with backticks, e.g. `@return`, as we don't want to bother github users by accidentally mentioning them in issues like this.

This change doesn't match what is shown in the official `libgit2` documentation, what do you think about applying this change to libgit2 upstream?

**Comment by vivaladav** [comment]
> As a gentle reminder, please try to quote any macro names with backticks

I will do, sorry about that. I created my GitHub account last night and this is my first contribution. I honestly didn't think about it.

> This change doesn't match what is shown in the official libgit2 documentation

The documentation is wrong, as you can see from the linked issue. That's the reason for the fix.

**Comment by carlosmn** [comment]
Thanks!

**Comment by ethomson** [comment]
> This change doesn't match what is shown in the official libgit2 documentation, what do you think about applying this change to libgit2 upstream?

To clarify: this _is_ a change to the documentation.  Our docs are automatically generated from the public headers, so this will update them.

**Comment by ethomson** [comment]
And thanks again @vivaladev :sparkles: !  Welcome to the libgit2 project!  :grinning:

**Comment by staticfloat** [comment]
My goodness, I was so confused. I thought I was in a completely different repository. Sorry for the noise! ;)

**Comment by vivaladav** [comment]
Thank you @ethomson 

I noticed this "bug" while trying to figure out why something doesn't work as expected with some patch functions. Hopefully I will be able to contribute more as soon as I get my head around it (I will open an issue at least).

**Pull request merged**
