### PR TITLE
Add a custom param to git_smart_subtransport_definition

### PR DESCRIPTION
**Pull request by leoyanggit**
A custom param will enable the implementer of a smart subtransport to store payload.

### CODE REVIEW

**Comment by ethomson** [comment]
Hmm.  It was intended that if you want to do something different, that you use a different `callback` in the definition (instead of using the same `callback` and switching on the `payload`)...

I'm curious as to what problem you have that a custom `payload` solves but simply using the `callback` doesn't.

**Comment by leoyanggit** [comment]
> Hmm. It was intended that if you want to do something different, that you use a different callback in the definition (instead of using the same callback and switching on the payload)...

No I'm not using the param to do something different by switching the param.

> I'm curious as to what problem you have that a custom payload solves but simply using the callback doesn't.

The current parameters - git_smart_subtransport **out and git_transport *owner - are not adequate to know about my actual transport/stream layer. I need something like a stream factory to create my custom stream that is associated to the sub transport . The creating process is very custom.

**Comment by ethomson** [comment]
Sure - the way you're expected to know about your actual transport is to use a different `callback` for each.  In the library itself, the HTTP creation callback is different than the SSH creation callback, etc.

Still, this conceptually seems reasonable, it provides a certain amount of parity with registering a non-smart-subtransport, since the smart subtransport creation function has eaten the param (since it's the smart subtransport definition).

However you're going to need to make the uses of the callbacks within the library reflect the updated signature.

/cc @carlosmn

**Comment by leoyanggit** [comment]
More precisely my problem is that the creating of sub transport stream is very complicated as a result I need the creation being a callback. But unfortunately as you said the param for the register has been taken by the smart transport itself. There is no way to callback in the sub transport.

**Comment by ethomson** [comment]
Sure.  I think that makes sense.  But we need to update all the smart subtransports within the library itself so they now accept this additional parameter.

**Comment by leoyanggit** [comment]
There is a failed check. How can I know the details of the failure? (Sorry I'm a github novice)

**Comment by ethomson** [comment]
In this case, it's our CI system being flakey.  (Click on "Show all checks", then "Details" to see the information, though it's not particularly informative.)

If you push up new commit(s) then the CI builds should kick off again.  I think that Travis has sorted their Mac build problems so they should pass.

**Comment by leoyanggit** [comment]
>  But we need to update all the smart subtransports within the library itself so they now accept this additional parameter.

You mean the initializer of git_smart_subtransport_definition? For example 
```
http_subtransport_definition = { git_smart_subtransport_http, 1 };
```
should be
```
http_subtransport_definition = { git_smart_subtransport_http, 1, NULL };
```
I think it's a good idea although it is also fine without the explicit NULL for this case.

**Comment by ethomson** [comment]
No.  I mean that `git_smart_subtransport_http` now takes an extra argument.

**Comment by leoyanggit** [comment]
Oh yes thanks. I forgot that one. I don't know how my compile passed. Maybe due to the weak type system in C :(

**Comment by leoyanggit** [comment]
Is the last failed check due to the flakiness of the CI system again or a real failure that I need to fix?

**Comment by ethomson** [comment]
Sorry I didn't see that you had pushed another commit - I'll restart the build.  The CI server was flaky earlier this week.

**Comment by leoyanggit** [comment]
Thanks!

**Comment by leoyanggit** [comment]
All checks passed.

**Pull request merged**
