### PR TITLE
Fast import APIs

### PR DESCRIPTION
**Pull request by arrbee**
This comes from working together with @barrbrain on adding fast import APIs into libgit2.  This is just an initial framework onto which we can add the full range of commands.

### CODE REVIEW

**Comment by Cactusinhand** [comment]
Hello, any update for this API?

**Comment by barrbrain** [comment]
It has been quite some time since I left GitHub, shortly after the last comment from @schu. I could enquire with my current employer about resuming libgit2 contribution.

**Comment by Cactusinhand** [comment]
> It has been quite some time since I left GitHub, shortly after the last comment from @schu. I could enquire with my current employer about resuming libgit2 contribution.

Thanks a lot!

**Comment by Cactusinhand** [comment]
Actual, my application rely on git-fast-export/import cmds, but this require the client to install specified version Git in their local. 
And now I want to use libgit2 to do all git operations in my application.

**Pull request closed without merging**
