### PR TITLE
Configuration entry iteration in order

### PR DESCRIPTION
**Pull request by pks-t**
I've finally pulled myself together and tackled my itch of iterating through configuration entries in the order they appear in the file. At first, I started getting annoyed again by the unnecessarily complex config file code, so I preceded the actual logic by quite a lot of refactoring and renaming of structures and functions. The result is actually very pleasant: while maintaining a second data structure alongside the map of entries, this PR still has more deletions than additions. So I definitly think that this PR helps a whole lot regarding readability.

### CODE REVIEW

**Comment by pks-t** [comment]
Small note: I highly recommend reviewing the commits one by one. There's a lot of renaming going on step by step, which becomes a whole lot easier to do if not reviewing the complete diff at once.

**Comment by ethomson** [comment]
Are you hoping that we land this for the immediate next release?  Seems like a Big Change and my preference would be to land it after we cut the next release, but I want to make sure we're both on the same page.

**Comment by pks-t** [comment]
We are on the same page ;)

**Comment by pks-t** [comment]
Rebased to fix merge conflicts with #4552

**Comment by ethomson** [comment]
> Small note: I highly recommend reviewing the commits one by one. There's a lot of renaming going on step by step, which becomes a whole lot easier to do if not reviewing the complete diff at once.

This was a good hint.  Reviewing each commit was helpful in seeing the progression.

Thanks for tackling this; there's some nice cleanup in here _and_ improved functionality.  👍

**Pull request merged**
