### PR TITLE
Fix compiling with Haiku

### PR DESCRIPTION
**Pull request by kainjow**

### CODE REVIEW

**Comment by pks-t** [comment]
I'd like to not include platform-specific logic whenever possible. This could be implemented as follows:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4bfd1b499..f31bdb28b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -464,7 +464,9 @@ IF (MSVC)
    # Precompiled headers
 
 ELSE ()
-	SET(CMAKE_C_FLAGS "-D_GNU_SOURCE -Wall -Wextra ${CMAKE_C_FLAGS}")
+	SET(CMAKE_C_FLAGS "-D_GNU_SOURCE -Wall ${CMAKE_C_FLAGS}")
+
+	ADD_C_FLAG_IF_SUPPORTED(-Wextra)
 
 	IF (CMAKE_SYSTEM_NAME MATCHES "(Solaris|SunOS)")
 		SET(CMAKE_C_FLAGS "-std=c99 -D_POSIX_C_SOURCE=200112L -D__EXTENSIONS__ -D_POSIX_PTHREAD_SEMANTICS ${CMAKE_C_FLAGS}")
```

**Comment by kainjow** [comment]
yeah that would be a better fix. I'll try it out and report back.

**Comment by kainjow** [comment]
That change works :+1:

**Comment by pks-t** [comment]
Want to change your PR accordingly or shall I just merge my own commit?

**Comment by kainjow** [comment]
You can do your own.

**Comment by pks-t** [comment]
Fixed via #4148

**Comment by pks-t** [comment]
By the way, thanks for reporting and the initial fix :+1:

**Pull request closed without merging**
