### PR TITLE
CMake modules not found when using libgit2 as cmake submodule

### PR DESCRIPTION
**Pull request by Murmele**
Use Project variable, otherwise when using libgit2 as submodule in another project, the paths are incorrect

When using libgit2 as cmake submodule in another project the following variables are set incorrectly:
- CMAKE_SOURCE_DIR
- CMAKE_BINARY_DIR
They are set to the source dir of the main project not of libtgit2

### CODE REVIEW

**Comment by ethomson** [comment]
Hmm.  Looks like there's a few build failures - our Xenial images have an older cmake, possibly a compatibility problem?

**Comment by Murmele** [comment]
I will check out what's the problem

**Comment by Qix-** [comment]
It's because you missed a number of usages of `CMAKE_SOURCE|BINARY_DIR`. #6146 supercedes this PR and has all of the variables fixed correctly.

**Comment by Qix-** [comment]
@ethomson this can be closed since it was fixed in #6146.

**Comment by ethomson** [comment]
Thanks @Murmele and @Qix- - apologies for the inconvenience.

**Pull request closed without merging**
