### PR TITLE
Buffer growing cleanups

### PR DESCRIPTION
**Pull request by pks-t**
Small-ish cleanups for growing buffers. While this is mostly done to silence Coverity, I think it even improves code by a tiny fraction.

### CODE REVIEW

**Comment by ethomson** [comment]
Seems reasonable to me.  One thing I noticed here is that the `ENSURE_SIZE` macro is pretty wacky...!

```
#define ENSURE_SIZE(b, d) \
    if ((d) > buf->asize && git_buf_grow(b, (d)) < 0)\
        return -1;
```

Notice the `buf` there instead of using the `b` argument...  turns out that we're real consistent with naming and didn't notice this!

**Comment by ethomson** [comment]
I'm going to merge this manually, with a fix for `ENSURE_SIZE`.

**Comment by pks-t** [comment]
Oh, good eye! That's just been waiting to explode. Seeing you didn't yet create the commit, I'll fix this up.

**Comment by ethomson** [comment]
Oddly, fixing that makes a unit test fail on Windows...!  I'm digging in now.

**Comment by ethomson** [comment]
But feel free to push a change to this branch - I'm curious if AppVeyor sees the same thing or if it's something bizarre on my machine.

**Comment by pks-t** [comment]
Oh, strange. Didn't get any errors on Linux.

**Comment by pks-t** [comment]
Taking a look at all calls to `ENSURE_SIZE`, it is always called with `buf`, so the generated code should always be the same.

**Comment by ethomson** [comment]
Yeah...  presumably something else entirely, but the `repo::discover` tests are failing to clean up their tempdir on my machine now...  Very odd.

**Comment by ethomson** [comment]
Failing for me in `origin/master` as well, so...  🤷‍♂️   No idea what's going on, but I'm going to assume it's isolated to my machine for now and we can go ahead and merge this as-is.

**Pull request merged**
