### PR TITLE
WinHTTP: support best auth mechanism

### LINKED ISSUE #4039: NTLM credentials not posted by libgit2 if Basic authorization header stay before NTLM header
### Reproduction steps
1. Setup git server (TFS 2017 OnPremise in my case) to return http headers in order then Basic over NTLM
```
WWW-Authenticate: Bearer
WWW-Authenticate: Basic realm="uk-tfs01.2gis.local"
WWW-Authenticate: NTLM
```

2. Use libgit2sharp with DefaultCredentials provider (internally call **git_cred_default_new**) to fetch remote data.

### Expected behavior
Fetch completed successfully

### Actual behavior
Get an error "Too many redirects or authentication replays"

### Version of libgit2
libgit2sharp 0.22 which uses libgit2 0.24 (sha 785d8c4)

### Operating system(s) tested
Windows 10 x64

### Comments
If I setup TFS 2017 to return http headers in order then NTLM over Basic
```
WWW-Authenticate: Bearer
WWW-Authenticate: NTLM
WWW-Authenticate: Basic realm="uk-tfs01.2gis.local"
```

then default credentials passed successfully, so I think this is a bug in libgit2, probably in code handling WinHTTP authentication.

I attached sample powershell script I used to test libgit2 behaviour: [gitfetch.zip](https://github.com/libgit2/libgit2/files/663092/gitfetch.zip), hope this helps.
Just put it to git controlled folder and run, it should fetch master branch from remote using DefaultCredentials.

### PR DESCRIPTION
**Pull request by ethomson**
For username/password credentials, support NTLM or Basic (in that order of priority).  Use the WinHTTP built-in authentication support for both, and maintain a bitfield of the supported mechanisms from the response.

Fixes #4039

### CODE REVIEW

**Comment by graffen** [comment]
Any chance someone can pull in this one soon? It's blocking for users of Gitkraken who have upgraded their TFS servers to 2017.

**Comment by ethomson** [comment]
FYI @carlosmn - I rebased this to resolve conflicts.

**Comment by MustafaJamal** [comment]
After fixing of this issue, when we should expect the fixing of following LibGit2Sharp issue:

https://github.com/libgit2/libgit2sharp/issues/1168

Can anyone please tell me as we are facing issues when using LibGit2Sharp with TFS2015/TFS2017.

Thanks!

**Comment by tkelman** [comment]
We can try to reduce this and report on its own, but x-ref https://github.com/JuliaLang/julia/pull/22681 we're seeing that after this change an empty username and password now gives a generic GIT_ERROR on Windows, whereas on other platforms (and Windows on prior versions of libgit2) it gives GIT_EAUTH. Is this an expected behavior change?

**Pull request merged**
