### PR TITLE
inttypes.h is built-in header file since MSVC 2013

### LINKED ISSUE #3476: Trouble with inttypes.h when trying to compile a program that uses system inttypes.h on Windows 8 with Visual Studio 2013
When compile a program which uses system inttypes.h on Windows 8 with Visual Studio 2013,
I get these error messages.

```
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\inttypes.h(34): error C2371: 'imaxdiv_t' : redefinition; different basic types
1>          c:\workspace\q4\external\sources\libgit2-0.22.2\include\git2\inttypes.h(54) : see declaration of 'imaxdiv_t'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\inttypes.h(36): error C2375: '_abs64' : redefinition; different linkage
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdlib.h(388) : see declaration of '_abs64'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\inttypes.h(37): error C2375: 'imaxdiv' : redefinition; different linkage
1>          c:\workspace\q4\external\sources\libgit2-0.22.2\include\git2\inttypes.h(284) : see declaration of 'imaxdiv'
```

### PR DESCRIPTION
**Pull request by linquize**
Fixes #3476

### CODE REVIEW

**Comment by carlosmn** [comment]
Why is it an issue that we include this version? CI builds with VS 2013 IIRC, and I've been using VS 2015 for quite some time, so what's the issue? This commit doesn't explain *why* we should include it.

**Comment by linquize** [comment]
@carlosmn Please see #3476 for details. the types defined in libgit2's `inttypes.h` collide with 

error C2371: 'imaxdiv_t' : redefinition; different basic types

**Comment by carlosmn** [comment]
That kind of information is what should be in the commit to say *why* we're doing it. A comment on a PR does not serve the same function.

**Comment by linquize** [comment]
Commit message updated @ 240a85c

**Pull request merged**
