### PR TITLE
[WIP] Status within subdir

### PR DESCRIPTION
**Pull request by joshaber**
This is a failing test where we get the status within a subdir and it reports changes that don’t exist.

### CODE REVIEW

**Comment by carlosmn** [comment]
I've narrowed down where this happens, but I'm still confused as to why.

For one we're re-using the index counter in `iterator_pathlist__match()` so we can end up missing the path we're after. But even when fixing that, we failt to match the prefix, even though we should.

For the tree-to-index iterator, we pass the arguments to the prefix comparison the wrong way around, so we check whether "zzz_new_dir/new_file" is a prefix of "zzz_new_dir".

In the case where we don't disable pathspec matching, we skip this function entirely so presumably that's why it works in that case. If you pass in exact paths, we find it in a bsearch and simply return that it matches. Just swapping the arguments in the comparison seems to break the worktree-to-index iterator, since in that case we actually have directories rather than full paths which does match correctly.

**Comment by carlosmn** [comment]
I've made this work for this test (and a few around it, let's see what CI says about the rest) but this is pretty terrible code. We're switching what we're doing depending on which side we detect is longer and is likely a directory...

**Comment by carlosmn** [comment]
Unsuprisingly this breaks other things. We should probably just claim directories aren't supported and figure out if we do want that featur (which we probably do).

**Comment by ethomson** [comment]
Yeah.  Faced with this issue and #3576, it's time for me to spend a little time digging in to iterators and refactoring them.

In the mean time, please avoid `ITERATOR_PATHLIST_NONE` when using tree iterators and directories as it appears that it will most certainly fail.  I'll ship you the [speedup loop](http://thedailywtf.com/articles/The-Speedup-Loop) for this soon.

**Comment by joshaber** [comment]
Should I close this out then, and open an issue?

**Comment by ethomson** [comment]
That would be great.  Please assign it to me, I'm working on refactoring this now.

**Comment by joshaber** [comment]
:boom:

**Pull request closed without merging**
