### PR TITLE
If work_dir is not specified, use repo_dir to test if symlink is supported

### PR DESCRIPTION
**Pull request by linquize**
If `work_dir` is not specified, use `repo_dir` to test if symlink is supported
This avoids temp file creation failure if current directory is readonly.

### CODE REVIEW

**Comment by ethomson** [comment]
My reading of the documentation suggests that the `workdir_path` field of `git_repository_init_options` is evaluated relative to `repo_path`, so yes, effectively we should be testing the repository path if `workdir_path` is set to an empty string.

Is that reading correct?  If so, setting `workdir_path` to the repository path would be so surprising that I would like to see some unit tests here.

**Comment by linquize** [comment]
I just use `GIT_REPOSITORY_INIT_OPTIONS_INIT` to call `git_repository_init_ext()`.
Or simply call `git_repository_init()`
so `workdir_path` is NULL

**Comment by linquize** [comment]
The variable I changed only affects symlink support detection. It is not used somewhere else, so no unit test is needed.

**Comment by ethomson** [comment]
The code you post explicitly tests `NULL` workdir_path.

**Comment by linquize** [comment]
Right! The purpose of this PR is to write the temp file to the correct dir

**Comment by ethomson** [comment]
When the user has set the working directory to the repository directory explicitly?  When would one do that?  Why?

Are you *actually* seeing this as a problem?  Or do you *think* it's a problem by looking at the code?  It does not appear to be the case that using `GIT_REPOSITORY_INIT_OPTIONS` would ever set `workdir_path` to an empty string, only to `NULL`.  Is that not accurate?

Had you described the rationale behind this change, that would be helpful.  But *more helpful would be a unit test*, which would have shown:

1. A failure of expected behavior before your change, and
2. The expected behavior succeeding after your change

And would have codified something so that we would not accidentally regress it in the future.

And yes, a unit test is needed.

**Comment by linquize** [comment]
Unit test added.

**Comment by carlosmn** [comment]
The diff in `src/repostiory.c` adds a check in case the workdir is an empty string, but I don't see this in the test you've added. In that case, you are in fact setting a non-empty string, which would mean you're not exercising the change. I also don't see how the hand-written fetch and reset are interesting for this use-case.

Why should we handle the case of an empty string differently from any other? The result should be the same if the worktree is specified as `"."`. Shouldn't we try to fix this in the general case?

**Comment by ethomson** [comment]
As @carlosmn mentions, your unit test fails to explain the problem that you are trying to solve.  After reverting 55c9f0e, it continues to pass.  So the test does not show how we are presently deficient.  Nor does the change in 55c9f0e appear to be necessary.

Like I asked before, do you think that there is a problem given a reading of the code, or are you actually seeing a problem?  If so, can you describe it?  Maybe we can help you find a solution to this problem.

**Comment by linquize** [comment]
I reverted 55c9f0e, and the unit test fails. So the test should be meaningful.

**Comment by ethomson** [comment]
What is the failure that you see?

**Comment by linquize** [comment]
```
Loaded 286 suites: 
Started
................................................................................................................F......................................................................................................................................................................................................................................................................................SS..................................................................................S.......................................................................................................................................................................................................................................S......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S.......................................................................................................................................................................................................................................................................................................S....................................................................................................................................................................................................................................................................................................................SSSSSS....

  1) Failure:
checkout::index::honor_coresymlinks_default [/home/user/Documents/libgit2/tests/checkout/index.c:176]
  link_size != strlen("new.txt")
  -1 != 7
```

**Comment by linquize** [comment]
The failure result is from Linux.

**Comment by ethomson** [comment]
I see.  Thank you for the unit test.  The summary here is that we're testing the working directory for ignore case even when creating a bare repository, without a working directory.  Is that correct?

I think it would be more readable to pass `NULL` to `repo_init_config` when we're initializing a bare repository.  eg, something like at https://github.com/libgit2/libgit2/blob/master/src/repository.c#L1621:

    const char *wd = (opts->flags & GIT_REPOSITORY_INIT_BARE) ? NULL : git_buf_cstr(&wd_path);

and in https://github.com/libgit2/libgit2/blob/master/src/repository.c#L1631 pass `wd` instead.

Does this seem reasonable to you?

That said, there is the larger issue that a non-NULL empty string is a legitimate (but bizarre) choice for a working directory path, meaning that (by my reading of the documentation) it would put the working directory inside the repository directory.

But I can understand that this issue you raised is a legitimate one and we need not worry about that in this PR.

Thanks for the unit test, it clarified the problem.

**Comment by linquize** [comment]
Updated to pass NULL if bare repository.

**Comment by ethomson** [comment]
Thanks for this!  :sparkles:

**Pull request merged**
