### PR TITLE
api: be explicit about our C linkage

### PR DESCRIPTION
**Pull request by ethomson**
C++ users expect to not have to worry too much about linkages.  Let's me explicit about ours.

### CODE REVIEW

**Comment by carlosmn** [comment]
We have this in the start and end macros for each file, so this exterior one shouldn't be necessary (ideally).

**Comment by ethomson** [comment]
Ah, yes, I forgot that's what `GIT_BEGIN_DECL` did.

We didn't do this for `inttypes.h`, since it's not really ours...  I wonder if there are others.

**Comment by pks-t** [comment]
» find include -type f -exec grep -L GIT_BEGIN_DECL '{}' \;
include/git2.h
include/git2/stdint.h
include/git2/inttypes.h
include/git2/version.h

So yes, there are at least some.

**Comment by ethomson** [comment]
`git2.h` doesn't include any declarations directly.  Nor does `version.h`.

`stdint.h` is only included by `inttypes.h`.

So this guard is really only needed around the `inttypes.h` inclusion.

**Comment by carlosmn** [comment]
The system-provided headers do their own extern definition, it's completely outside of libgit2's responsibility to make the system's headers behave nicely with C++ in either case.

**Pull request merged**
