### PR TITLE
WinHTTP: Try to detect and use system configured proxy

### PR DESCRIPTION
**Pull request by csware**
If not proxy is configured in git config, try to detect WinHTTP and current user (IE) default proxy.

Web Proxy Auto-Discovery (WPAD) protocol not supported so far as it required deeper changes.

### CODE REVIEW

**Comment by ethomson** [comment]
I understand - and respect - the desire to put this into libgit2 somewhere so that consumers don't have to needlessly reimplement this.

We're in agreement that this should not be the default.

As @carlosmn has noted, a function to apply the default proxy seems like a reasonable approach.  Does this make sense?

**Comment by carlosmn** [comment]
With the new options structure coming in in #3066 it should make it easier to add an option there to auto-detect the proxy, or override it.

**Comment by newburyport** [comment]
I would like to know if this solution solves the proxy issue on Mac (OS X) too.

**Comment by carlosmn** [comment]
The Windows HTTP stack is not available on OS X.

**Comment by cbargren** [comment]
Would it make sense to reevaluate this change now that #3110 is in? I'd imagine that this change would make a lot of sense underneath the `GIT_PROXY_AUTO` umbrella and after it's been verified that the user doesn't have anything specified in their git config/env vars.

**Comment by ethomson** [comment]
This was (unintentionally) closed as part of renaming the master branch to main.

Reopened as #5774

**Pull request closed without merging**
