### PR TITLE
checkout: notify for deleted files

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by Murmele** [comment]
what is the current status of it?

**Comment by KOLANICH** [comment]
IDK. This patch was a part of the fork of libgit used in GitAhead git GUI. Now GitAhead is dead and its alive fork is GittyUp. It is likely it also contains this patch. But having own forks of libs within apps is a very unhealthy situation. It must not be done this way. So I tried to upstream the patches in the hope to make the moment when the tools use the same lib the whole system uses closer.

**Comment by Murmele** [comment]
I am one of the maintainer of Gittyup, I try to get rid of all of those patches and try to update libgit version to the most current one

**Comment by KOLANICH** [comment]
@Murmele, I guess I should close this PR because I have neither time to work on it nor experience with libgit2. So probably the most optimal solution for you is to create an own one.

**Comment by Murmele** [comment]
@KOLANICH yes I already started with it

**Pull request closed without merging**
