### PR TITLE
Introduce a GitHub Issue Template

### PR DESCRIPTION
**Pull request by ethomson**
Encourage people to ask questions on StackOverflow and use Issues for bug reports.

cc @carlosmn

### CODE REVIEW

**Comment by pks-t** [comment]
I'd like to have the user specify on which version he tried whatever he did, as not everybody is always using the latest release. I'd also put the reproduction steps first and have the actual/expected results afterwards, as this is a more natural flow.

**Comment by carlosmn** [comment]
+1 on asking the version. We might also want to add something about not opening bugs because some program is using libgit2 and it seems to be missing a feature. Unless you are a developer using libgit2, we can't help you.

**Comment by ethomson** [comment]
I've rearranged the headers, and asked now for the version being used (release or SHA1 built from) and the operating system(s) that show the behavior.

**Comment by pks-t** [comment]
I'd again re-arrange things a bit. Reproduction steps and expected/observed behavior certainly belong together, so I'd rather rearrange version/operating system to either come before or after the other three points. Looks good, other than that :)

**Comment by ethomson** [comment]
Yep, good call @pks-t - I've re-rearranged things.  :D

**Pull request merged**
