### PR TITLE
revwalk: detect when we're out of interesting commits

### PR DESCRIPTION
**Pull request by carlosmn**
When walking backwards and marking parents uninteresting, make sure we
detect when the list of commits we have left has run out of
uninteresting commits so we can stop marking commits as
uninteresting. Failing to do so can mean that we walk the whole history
marking everything uninteresting, which eats up time, CPU and IO for
with useless work.

While pre-marking does look for this, we still need to check during the
main traversal as there are setups for which pre-marking does not leave
enough information in the commits. This can happen if we push a commit
and hide its parent.

### CODE REVIEW

**Comment by ethomson** [comment]
:sparkles:

**Comment by ethomson** [comment]
As you noted in #3034:

> We don't have perf tests for this so I'm not sure we have a good way to avoid this kind of thing creeping up again.

I don't have a good way to avoid regressing here either.  Perf-based unit tests sound like a bad idea.  I've really got nothin', and my inclination is just to hit the shiny green merge button, but I thought I would delay a little bit in case anybody had a clever idea.

**Comment by carlosmn** [comment]
I can think of a couple, but I'm not a huge fan of either. We can do some tests against linux.git which we know should finish fairly quickly (<20ms) and then make it fail if it takes over 200ms. An order of maginute longer waits would mean that either the IO contention on the host is ridiculous or we've regressed badly. This would however not show smaller slowdowns.

Another approach is to regularly (say on each merge to master) perform some operations and graph the time they take. This would show smaller slowdowns and give us a rough view of the direction we're going performance-wise. We already have some instrumentation for this in clar, but I'm not volunteering to set up the infrastructure to keep this data.

**Comment by ethomson** [comment]
One of the Microsofties will, as part of the whole benchmarky stuff we've been doing.

**Comment by ethomson** [comment]
I really like that graphing idea, actually...!  Very exciting.

**Comment by YueLinHo** [comment]
A cross reference: [limit_list() in git.git](https://github.com/git/git/blob/master/revision.c#L1111)
Just viewed it few days ago. :)

**Pull request merged**
