### PR TITLE
Access HEAD via the refdb backends

### PR DESCRIPTION
**Pull request by pks-t**
There's quite a few places where we're accessing HEAD directly via the filesystem, which is completely broken in case repos use a different refdb backend than the filesystem-based one. This pull request addresses a subset of these which is updating HEAD in the context of worktrees.

### CODE REVIEW

**Comment by ethomson** [comment]
This looks good to me.  One possible addition is that I didn't see a test for renaming the thing that `HEAD` points to in our existing tree.  I assumed that the new rename code would take care of the simple case via the iterator, but it wasn't immediately 💯 clear to me.  So I added this just to better understand what was going on.

Possible that I simply missed the existing test or that the worktree tests cover this case satisfactorily.  But in case it's useful...

```
diff --git a/tests/refs/rename.c b/tests/refs/rename.c
index b1b75cd64..2f1667060 100644
--- a/tests/refs/rename.c
+++ b/tests/refs/rename.c
@@ -14,6 +14,7 @@ static const char *ref_one_name_new = "refs/heads/two/branch";
 static const char *ref_two_name = "refs/heads/two";
 static const char *ref_master_name = "refs/heads/master";
 static const char *ref_two_name_new = "refs/heads/two/two";
+static const char *ref_head_new = "refs/heads/main";

 static git_repository *g_repo;

@@ -366,3 +367,20 @@ void test_refs_rename__propagate_eexists(void)

    git_reference_free(ref);
 }
+
+void test_refs_rename__updates_head(void)
+{
+   git_reference *orig_head, *new_head, *renamed;
+
+   cl_git_pass(git_repository_head(&orig_head, g_repo));
+
+   cl_git_pass(git_reference_rename(&renamed, orig_head, ref_head_new, 0, NULL));
+
+   cl_git_pass(git_repository_head(&new_head, g_repo));
+
+   cl_assert_equal_s(ref_head_new, git_reference_name(new_head));
+
+   git_reference_free(new_head);
+   git_reference_free(renamed);
+   git_reference_free(orig_head);
+}
```

**Comment by pks-t** [comment]
On Fri, Jul 10, 2020 at 01:42:41AM -0700, Edward Thomson wrote:
> This looks good to me.  One possible addition is that I didn't see a test for renaming the thing that `HEAD` points to in our existing tree.  I assumed that the new rename code would take care of the simple case via the iterator, but it wasn't immediately 💯 clear to me.  So I added this just to better understand what was going on.
> 
> Possible that I simply missed the existing test or that the worktree tests cover this case satisfactorily.  But in case it's useful...
> 
> ```diff
> diff --git a/tests/refs/rename.c b/tests/refs/rename.c
> index b1b75cd64..2f1667060 100644
> --- a/tests/refs/rename.c
> +++ b/tests/refs/rename.c
> @@ -14,6 +14,7 @@ static const char *ref_one_name_new = "refs/heads/two/branch";
>  static const char *ref_two_name = "refs/heads/two";
>  static const char *ref_master_name = "refs/heads/master";
>  static const char *ref_two_name_new = "refs/heads/two/two";
> +static const char *ref_head_new = "refs/heads/main";
> 
>  static git_repository *g_repo;
> 
> @@ -366,3 +367,20 @@ void test_refs_rename__propagate_eexists(void)
> 
>     git_reference_free(ref);
>  }
> +
> +void test_refs_rename__updates_head(void)
> +{
> +   git_reference *orig_head, *new_head, *renamed;
> +
> +   cl_git_pass(git_repository_head(&orig_head, g_repo));
> +
> +   cl_git_pass(git_reference_rename(&renamed, orig_head, ref_head_new, 0, NULL));
> +
> +   cl_git_pass(git_repository_head(&new_head, g_repo));
> +
> +   cl_assert_equal_s(ref_head_new, git_reference_name(new_head));
> +
> +   git_reference_free(new_head);
> +   git_reference_free(renamed);
> +   git_reference_free(orig_head);
> +}

We do have that in worktree::refs::renaming_reference_updates_worktree_heads,
if I get right what you want to test:

```
void test_worktree_refs__renaming_reference_updates_worktree_heads(void)
{
	git_reference *head, *branch, *renamed;

	cl_git_pass(git_branch_lookup(&branch, fixture.repo,
		    "testrepo-worktree", GIT_BRANCH_LOCAL));
	cl_git_pass(git_reference_rename(&renamed, branch, "refs/heads/renamed", 0, NULL));
	cl_git_pass(git_repository_head(&head, fixture.worktree));

	git_reference_free(head);
	git_reference_free(branch);
	git_reference_free(renamed);
}
```

Except that we don't verify what the worktree's renamed HEAD points to
now. If I add the `equal_s` there, would that test what you expect?

**Comment by ethomson** [comment]
> Except that we don't verify what the worktree's renamed HEAD points to now. If I add the `equal_s` there, would that test what you expect?

Yes, it looks like it would.

**Comment by pks-t** [comment]
Huh, both `git_repository_head` and `git_repository_worktree_head` are really weird. They won't return `HEAD`, but resolve `HEAD` to their respective target reference. I wonder who'd actually expect, much less want that to happen. Anyway, this is not a new problem introduced by this series.

I've updated the testcase we have and rebased my PR on latest master to check there's no bad interactions with the other PRs which got merged meanwhile.

**Pull request merged**
