### PR TITLE
Fix 8.3 filename tests failure when 8.3 is disabled

### PR DESCRIPTION
**Pull request by linquize**
Fix 8.3 filename tests failure when 8.3 is disabled

### CODE REVIEW

**Comment by ethomson** [comment]
I don't understand.  Is there just a test failure?  What test?  Why?

We shouldn't include `.git` in the list of shortnames.  That's already a prohibited name.  If this is just working around a test failure then we should fix the test.

**Comment by linquize** [comment]
`test_repo_reservedname__includes_shortname_on_win32` and 
`test_repo_reservedname__includes_shortname_when_requested`

`cl_assert_equal_i(2, reserved_len);`
but `reserved_len` was 3

**Comment by linquize** [comment]
because it added ".git" to the end of the list (repeated), so `reserved_len` was 3

**Comment by ethomson** [comment]
I see.  Out of curiosity, what system / filesystem is that?

**Comment by linquize** [comment]
win 8 x64, NTFS

**Pull request merged**
