### PR TITLE
repository: use intptr_t's in the config map cache

### LINKED ISSUE #5745: Regression: libgit2 crashes on Windows arm64
### Reproduction steps

1. Use [git2-rs](https://github.com/rust-lang/git2-rs) v0.13.13 in a Rust project. This version references libgit2-sys v0.12.15 which includes the merge commit that breaks the functionality.
2. Try to clone the repository using Rust's API `Repository::clone` which calls `git_clone` from libgit2.

### Expected behavior

The repository is cloned successfully.

### Actual behavior

```
error: process didn't exit successfully: `target\debug\git2-test.exe clone https://github.com/rust-lang/git2-rs.git C:\Projects\my-git2-rs-2` (exit code: 0x80000002)
```

### Version of libgit2 (release number or SHA1)

5699ef81942538bc24df5285876e5830570b65f3

### Operating system(s) tested

Windows 10 arm64

### Additional information

Updating libgit2 submodule of git2-rs commit by commit I found out that the following PR is the culprit:

https://github.com/libgit2/libgit2/pull/5595
https://github.com/libgit2/libgit2/commit/5699ef81942538bc24df5285876e5830570b65f3

I can't say I understand very well what's going on there but I'll do my best to at least find the exact place where it crashes.

If you need to use my device (Surface Pro X) to debug, please let me know.

### PR DESCRIPTION
**Pull request by ethomson**
Since we're using atomic primitives to read and write into the config map cache, we need to read/write something pointer-sized.  Use an `intptr_t` for the config map cache.

Fixes #5745

### CODE REVIEW

**Review by lhchavez — APPROVED** [review]
nice! ~i'm still trying to flash a RPi4 with a 64-bit OS, but this seems like the right fix.~ libgit2_clar on Linux/arm64 passes with this (and the patch I mentioned below)

**Comment by Alovchin91** [comment]
Works for me @ethomson 👍 I'm gonna try to run the full libgit2 test suite on my Surface Pro X now, if I'll manage to build it here...

**Comment by lhchavez** [comment]
oh wait, i just realized something. can we add something along the lines of

```diff
diff --git a/src/config_cache.c b/src/config_cache.c
index 2f0455af9..0ea7d80dc 100644
--- a/src/config_cache.c
+++ b/src/config_cache.c
@@ -111,18 +111,21 @@ int git_config__configmap_lookup(int *out, git_config *config, git_configmap_ite
 
 int git_repository__configmap_lookup(int *out, git_repository *repo, git_configmap_item item)
 {
-       *out = (int)(intptr_t)git_atomic_load(repo->configmap_cache[(int)item]);
+       intptr_t value = (intptr_t)git_atomic_load(repo->configmap_cache[(int)item]);
+       *out = (int)value;
 
-       if (*out == GIT_CONFIGMAP_NOT_CACHED) {
+       if (value == GIT_CONFIGMAP_NOT_CACHED) {
                int error;
-               int oldval = GIT_CONFIGMAP_NOT_CACHED;
+               intptr_t oldval = GIT_CONFIGMAP_NOT_CACHED;
                git_config *config;
 
                if ((error = git_repository_config__weakptr(&config, repo)) < 0 ||
                        (error = git_config__configmap_lookup(out, config, item)) < 0)
                        return error;
 
-               git_atomic_compare_and_swap(&repo->configmap_cache[(int)item], &oldval, out);
+               value = *out;
+               git_atomic_compare_and_swap(&repo->configmap_cache[(int)item], &oldval, &value);
+               *out = value;
        }
 
        return 0;
```

(give me a second to actually test this bit). i can also try to add it in a separate PR if preferable.

**Comment by Alovchin91** [comment]
I've built libgit2 with the following configuration:

<details>
  <summary><code>cmake -G "Visual Studio 16 2019" -A ARM64 -DWIN32_LEAKCHECK=ON -DDEPRECATE_HARD=ON ..\libgit2</code></summary>

```
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29335.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29333/bin/Hostx86/arm64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
    Reason given by package: The command
      "C:/Strawberry/perl/bin/pkg-config" --version
    failed with output


-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Failed
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Failed
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
-- Performing Test IS_WMISSING_DECLARATIONS_SUPPORTED
-- Performing Test IS_WMISSING_DECLARATIONS_SUPPORTED - Failed
-- Looking for futimens
-- Looking for futimens - not found
-- Checking prototype qsort_r for HAVE_QSORT_R_BSD
-- Checking prototype qsort_r for HAVE_QSORT_R_BSD - False
-- Checking prototype qsort_r for HAVE_QSORT_R_GNU
-- Checking prototype qsort_r for HAVE_QSORT_R_GNU - False
-- Looking for qsort_s
-- Looking for qsort_s - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found version "1.1.1g")
-- Could NOT find PCRE (missing: PCRE_LIBRARY PCRE_POSIX_LIBRARY PCRE_INCLUDE_DIR)
-- Looking for regcomp_l
-- Looking for regcomp_l - not found
-- Looking for dirent.h
-- Looking for dirent.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for windows.h
-- Looking for windows.h - found
-- Looking for bcopy
-- Looking for bcopy - not found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for strtoq
-- Looking for strtoq - not found
-- Looking for _strtoi64
-- Looking for _strtoi64 - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Performing Test IS_WNO_UNUSED_FUNCTION_SUPPORTED
-- Performing Test IS_WNO_UNUSED_FUNCTION_SUPPORTED - Failed
-- Performing Test IS_WNO_IMPLICIT_FALLTHROUGH_SUPPORTED
-- Performing Test IS_WNO_IMPLICIT_FALLTHROUGH_SUPPORTED - Failed
-- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED - Failed
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
-- zlib was not found; using bundled 3rd-party sources.
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
-- Could NOT find GSSAPI (missing: GSSAPI_LIBRARIES GSSAPI_INCLUDE_DIR)
-- Found PythonInterp: C:/Projects/python-3.9.1-embed-win32/python.exe (found version "3.9.1")
-- Enabled features:
 * nanoseconds, whether to use sub-second file mtimes and ctimes
 * tracing, tracing support
 * threadsafe, threadsafe support
 * HTTPS, using WinHTTP
 * SHA, using CollisionDetection
 * regex, using bundled PCRE
 * http-parser, http-parser support (bundled)
 * zlib, using bundled zlib

-- Disabled features:
 * debugpool, debug pool allocator
 * SSH, SSH transport support
 * ntlmclient, NTLM authentication support for Unix
 * SPNEGO, SPNEGO authentication support
 * iconv, iconv encoding conversion support

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Projects/libgit2_build
```

</details>

And almost all tests succeeded except for `trace::windows::stacktrace::leaks`:

<details>
  <summary><code>ctest -V</code></summary>

```
UpdateCTestConfiguration  from :C:/Projects/libgit2_build/DartConfiguration.tcl
UpdateCTestConfiguration  from :C:/Projects/libgit2_build/DartConfiguration.tcl
Test project C:/Projects/libgit2_build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: offline

1: Test command: C:\Projects\libgit2_build\RelWithDebInfo\libgit2_clar.exe "-v" "-xonline"
1: Test timeout computed to be: 10000000
1: Loaded 392 suites:
1: Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
1:
1: apply::both......S...................
1: apply::callbacks...
1: apply::check....
1: apply::fromdiff..........................
1: apply::fromfile..........................................
1: apply::index.........
1: apply::partial............
1: apply::tree..
1: apply::workdir...........
1: attr::file.....
1: attr::flags...
1: attr::lookup.....
1: attr::macro.........
1: attr::repo.............
1: blame::buffer.......
1: blame::getters..
1: blame::harder....
1: blame::simple...........
1: buf::basic...
1: buf::oom..
1: buf::percent..
1: buf::quote...
1: buf::splice.........
1: checkout::binaryunicode..
1: checkout::conflict.................
1: checkout::crlf..............
1: checkout::head...........
1: checkout::icase.............
1: checkout::index.......S..S.....................
1: checkout::nasty................................
1: checkout::tree...............................S.........S...
1: checkout::typechange...
1: cherrypick::bare...
1: cherrypick::workdir..........
1: clone::empty....
1: clone::local....
1: clone::nonetwork..................
1: clone::transport.
1: commit::commit.....
1: commit::parent.
1: commit::parse........
1: commit::signature............
1: commit::write........
1: config::add..
1: config::backend.
1: config::conditionals....
1: config::configlevel....
1: config::global.....
1: config::include...............
1: config::memory.......
1: config::multivar.........
1: config::new.
1: config::read................................................
1: config::readonly...
1: config::rename...
1: config::snapshot.....
1: config::stress........S
1: config::validkeyname.
1: config::write..........................
1: core::array.
1: core::assert....
1: core::bitvec.
1: core::buffer............................
1: core::copy...
1: core::dirent.........
1: core::encoding..
1: core::env....
1: core::errors........
1: core::features.
1: core::filebuf.......SSS..
1: core::ftruncateSS
1: core::futils..S
1: core::hex.
1: core::iconv...
1: core::init...
1: core::link..SSSSSSSSS....SS....SSS
1: core::memmem...
1: core::mkdir......
1: core::oid...
1: core::oidmap......
1: core::opts..
1: core::path................
1: core::pool....
1: core::posix..SSSS
1: core::pqueue.....
1: core::qsort......
1: core::regexp.SSS..........
1: core::rmdir.....
1: core::sha1..
1: core::sortedcache...
1: core::stat..
1: core::string.......
1: core::strmap...........
1: core::strtol........
1: core::structinitS
1: core::useragent.
1: core::vector..........
1: core::wildmatch........
1: core::zstream....
1: date::date.
1: date::rfc2822....
1: delta::apply..
1: describe::describe..
1: describe::t6120.......
1: diff::binary............
1: diff::blob...................
1: diff::diffiter.........
1: diff::drivers....
1: diff::format::email.........
1: diff::index.......
1: diff::notify.......
1: diff::parse...............
1: diff::patch.......
1: diff::patchid...........
1: diff::pathspec.
1: diff::racediffiter..
1: diff::rename.............................
1: diff::stats.................
1: diff::submodules.........
1: diff::tree............
1: diff::workdir..............................
1: fetchhead::nonetwork................
1: filter::bare....
1: filter::blob....
1: filter::crlf......
1: filter::custom......
1: filter::file..
1: filter::ident..
1: filter::query....
1: filter::stream.S
1: filter::systemattrs..
1: filter::wildcard...
1: graph::ahead::behind.
1: graph::descendant::of..
1: ignore::path...................S...............
1: ignore::status......................................
1: index::add.
1: index::addall......
1: index::bypath.............
1: index::cache.....
1: index::collision....
1: index::conflicts............
1: index::crlf..........
1: index::filemodes......
1: index::inmemory..
1: index::names.......
1: index::nsec...
1: index::racy.........
1: index::read::index....
1: index::read::tree.
1: index::rename..
1: index::reuc..............
1: index::splitindex.
1: index::stage..
1: index::tests..................................
1: index::version...
1: iterator::index.......................
1: iterator::tree........................
1: iterator::workdir.................S.S..........
1: mailmap::basic.....
1: mailmap::blame..
1: mailmap::parsing.......
1: merge::analysis (with bare repository).........
1: merge::analysis (with nonbare repository).........
1: merge::annotated::commit.
1: merge::driver............
1: merge::files...........
1: merge::trees::automerge....
1: merge::trees::commits....
1: merge::trees::modeconflict.
1: merge::trees::recursive..................
1: merge::trees::renames....
1: merge::trees::treediff.....
1: merge::trees::trivial.............
1: merge::trees::whitespace...
1: merge::workdir::dirty......
1: merge::workdir::recursive..
1: merge::workdir::renames...
1: merge::workdir::setup................................
1: merge::workdir::simple................
1: merge::workdir::submodules...
1: merge::workdir::trivial.............
1: message::trailer.........
1: network::cred...
1: network::fetchlocal............
1: network::joinpath......
1: network::matchhost.
1: network::redirect..........
1: network::refspecs.........
1: network::remote::defaultbranch......
1: network::remote::delete...
1: network::remote::isvalidname..
1: network::remote::local...................
1: network::remote::push..
1: network::remote::remotes........................
1: network::remote::rename.............
1: network::urlparse............
1: notes::notes.......................
1: notes::notesref.
1: object::blob::filter...
1: object::blob::fromstream..
1: object::blob::write...
1: object::cache (cache no blobs)...
1: object::cache (cache tiny blobs)...
1: object::cache (cache all blobs)...
1: object::cache (cache no trees)...
1: object::commit::commitstagedfile..
1: object::commit::parse...........
1: object::lookup......
1: object::lookupbypath....
1: object::message................
1: object::peel......
1: object::raw::chars..
1: object::raw::compare.......
1: object::raw::convert...
1: object::raw::fromstr..
1: object::raw::hash...........
1: object::raw::short...
1: object::raw::size.
1: object::raw::type2string...
1: object::raw::write.......
1: object::shortid.
1: object::tag::list..
1: object::tag::parse............
1: object::tag::peel...
1: object::tag::read.....
1: object::tag::write..........
1: object::tree::attributes.....
1: object::tree::duplicateentries..
1: object::tree::frompath..
1: object::tree::parse..............
1: object::tree::read..S
1: object::tree::update.........
1: object::tree::walk...
1: object::tree::write.........
1: odb::alternates..
1: odb::backend::mempack.....
1: odb::backend::multiple.....
1: odb::backend::nobackend.
1: odb::backend::nonrefreshing.........
1: odb::backend::simple..............
1: odb::emptyobjects...
1: odb::foreach....
1: odb::freshen.....
1: odb::largefilesSSSSSS
1: odb::loose..........
1: odb::mixed....
1: odb::packed...
1: odb::packed::one..
1: odb::sorting..
1: odb::streamwrite...
1: pack::filelimit (tiny).
1: pack::filelimit (medium).
1: pack::filelimit (unlimited).
1: pack::indexer........
1: pack::midx..
1: pack::packbuilder............
1: pack::sharing.
1: pack::threadsafety.
1: patch::parse.................
1: patch::print...........................
1: path::core................
1: path::dotgit..
1: path::win32............
1: rebase::abort.......
1: rebase::inmemory....
1: rebase::iterator..
1: rebase::merge...................
1: rebase::setup..............
1: rebase::sign...
1: rebase::submodule.
1: refs::basic.
1: refs::branches::checkedout....
1: refs::branches::create.........
1: refs::branches::delete.........
1: refs::branches::ishead......
1: refs::branches::iterator.....
1: refs::branches::lookup........
1: refs::branches::move..........
1: refs::branches::name...
1: refs::branches::remote....
1: refs::branches::upstream..........
1: refs::branches::upstreamname..
1: refs::crashes.
1: refs::create.............
1: refs::delete....
1: refs::dup..
1: refs::foreachglob......
1: refs::isvalidname..
1: refs::iterator...S....
1: refs::list..
1: refs::listall...
1: refs::lookup.....
1: refs::namespaces..
1: refs::normalize......
1: refs::overwrite....
1: refs::pack...
1: refs::peel.......
1: refs::races.....
1: refs::read...............
1: refs::reflog::drop.......
1: refs::reflog::messages..............
1: refs::reflog::reflog..................
1: refs::rename...........
1: refs::revparse.................................
1: refs::setter....
1: refs::shorthand.
1: refs::transactions.........
1: refs::unicode.
1: refs::update.
1: remote::create......................
1: remote::insteadof.....
1: remote::list.
1: repo::config...
1: repo::discover..........
1: repo::env.
1: repo::getters...
1: repo::hashfile..
1: repo::head...............
1: repo::headtree....
1: repo::init..........S.S..........S..S.
1: repo::message..
1: repo::new..
1: repo::open..........S......
1: repo::pathspec..........
1: repo::reservedname.....
1: repo::setters.....
1: repo::shallow....
1: repo::state.............
1: repo::template.......
1: reset::default.....
1: reset::hard......
1: reset::mixed...
1: reset::soft.........
1: revert::bare...
1: revert::workdir...............
1: revwalk::basic.......................
1: revwalk::hidecb.......
1: revwalk::mergebase..............
1: revwalk::signatureparsing.
1: revwalk::simplify.
1: stash::apply...................
1: stash::drop.......
1: stash::foreach..
1: stash::save..................
1: stash::submodules..
1: status::renames................
1: status::single..
1: status::submodules...........
1: status::worktree.....................................SS....
1: status::worktree::init........
1: stream::deprecated.
1: stream::registration...
1: submodule::add.........
1: submodule::escape..
1: submodule::init...
1: submodule::inject::option..
1: submodule::lookup..............
1: submodule::modify........
1: submodule::nosubs.....
1: submodule::open...
1: submodule::repository::init.
1: submodule::status.......
1: submodule::update.......
1: threads::basic....
1: threads::diff..
1: threads::iterator.
1: threads::refdb.
1: threads::tlsdata..
1: trace::trace......
1: trace::windows::stacktrace.F.
1: transport::register....
1: transports::smart::packet.............
1: win32::forbidden..........
1: win32::longpath.
1: worktree::bare...
1: worktree::config..
1: worktree::merge...
1: worktree::open........
1: worktree::reflog....
1: worktree::refs............
1: worktree::repository....
1: worktree::submodule....
1: worktree::worktree..................................
1:
1:   1) Failure:
1: trace::windows::stacktrace::leaks [C:\Projects\libgit2\tests\trace\windows\stacktrace.c:60]
1:   1 != leaks
1:   1 != 0
1:
1/8 Test #1: offline ..........................***Failed  714.92 sec
test 2
    Start 2: invasive

2: Test command: C:\Projects\libgit2_build\RelWithDebInfo\libgit2_clar.exe "-v" "-score::ftruncate" "-sfilter::stream::bigfile" "-sodb::largefiles" "-siterator::workdir::filesystem_gunk" "-srepo::init" "-srepo::init::at_filesystem_root"
2: Test timeout computed to be: 10000000
2: Loaded 392 suites:
2: Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
2:
2: core::ftruncateSS
2: filter::streamS
2: odb::largefilesSSSSSS
2: iterator::workdirS
2: repo::init..........S.S..........S..S.
2: repo::initS
2:
2/8 Test #2: invasive .........................   Passed    1.99 sec
test 3
    Start 3: online

3: Test command: C:\Projects\libgit2_build\RelWithDebInfo\libgit2_clar.exe "-v" "-sonline"
3: Test timeout computed to be: 10000000
3: Loaded 392 suites:
3: Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
3:
3: online::badssl....
3: online::clone.........S...S..SSSSS...SSS.S..
3: online::fetch...........
3: online::fetchhead.......
3: online::pushSSSSSSSSSSSSSSSSSSSSS
3: online::remotes......
3:
3/8 Test #3: online ...........................   Passed   67.62 sec
test 4
    Start 4: gitdaemon

4: Test command: C:\Projects\libgit2_build\RelWithDebInfo\libgit2_clar.exe "-v" "-sonline::push"
4: Test timeout computed to be: 10000000
4: Loaded 392 suites:
4: Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
4:
4: online::pushSSSSSSSSSSSSSSSSSSSSS
4:
4/8 Test #4: gitdaemon ........................   Passed    8.87 sec
test 5
    Start 5: ssh

5: Test command: C:\Projects\libgit2_build\RelWithDebInfo\libgit2_clar.exe "-v" "-sonline::push" "-sonline::clone::ssh_cert" "-sonline::clone::ssh_with_paths" "-sonline::clone::path_whitespace_ssh"
5: Test timeout computed to be: 10000000
5: Loaded 392 suites:
5: Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
5:
5: online::pushSSSSSSSSSSSSSSSSSSSSS
5: online::cloneS
5: online::cloneS
5: online::clone
5:
5/8 Test #5: ssh ..............................   Passed   11.40 sec
test 6
    Start 6: proxy

6: Test command: C:\Projects\libgit2_build\RelWithDebInfo\libgit2_clar.exe "-v" "-sonline::clone::proxy"
6: Test timeout computed to be: 10000000
6: Loaded 392 suites:
6: Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
6:
6: online::cloneSSS.S
6:
6/8 Test #6: proxy ............................   Passed    1.39 sec
test 7
    Start 7: auth_clone

7: Test command: C:\Projects\libgit2_build\RelWithDebInfo\libgit2_clar.exe "-v" "-sonline::clone::cred"
7: Test timeout computed to be: 10000000
7: Loaded 392 suites:
7: Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
7:
7: online::clone..S.
7:
7/8 Test #7: auth_clone .......................   Passed    3.85 sec
test 8
    Start 8: auth_clone_and_push

8: Test command: C:\Projects\libgit2_build\RelWithDebInfo\libgit2_clar.exe "-v" "-sonline::clone::push" "-sonline::push"
8: Test timeout computed to be: 10000000
8: Loaded 392 suites:
8: Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
8:
8: online::clone
8: online::pushSSSSSSSSSSSSSSSSSSSSS
8:
8/8 Test #8: auth_clone_and_push ..............   Passed   11.24 sec

88% tests passed, 1 tests failed out of 8

Total Test time (real) = 821.42 sec

The following tests FAILED:
          1 - offline (Failed)
Errors while running CTest
```

</details>

**Review by Alovchin91 — APPROVED** [review]

**Comment by ethomson** [comment]
Yep, I like that change, @lhchavez.  I'm including it.

**Comment by ethomson** [comment]
One thing that I'm a little concerned about @Alovchin91 - you're using MSVC:

```
cmake -G "Visual Studio 16 2019" -A ARM64 -DWIN32_LEAKCHECK=ON -DDEPRECATE_HARD=ON ..\libgit2
```

which I _think_ will mean that you use the `InterlockedCompareExchange` function instead of the gcc/clang intrinsics.  I think that those might have succeeded prior to this change?  I think that you may need to build with mingw to get the gcc style intrinsics.

I'm going to merge this optimistically, because it _at least_ fixes a problem on Sparc.

**Comment by Alovchin91** [comment]
@ethomson I don't think **gcc** supports building for Windows arm64. I could use @mstorsjo's [llvm-mingw](https://github.com/mstorsjo/llvm-mingw) to build libgit2 and run all tests, but please note that the whole topic originated from Rust's **git2-rs**, and Rust doesn't have any toolchains for Windows arm64 except for MSVC.

**Comment by mstorsjo** [comment]
> but please note that the whole topic originated from Rust's **git2-rs**, and Rust doesn't have any toolchains for Windows arm64 except for MSVC.

FWIW, with LLVM based tools, I do believe that rust should work for aarch64-windows-gnu (aka aarch64-w64-mingw32) targets more or less, it's just not a very supported target. I'm not really familiar enough with it to know off-hand how to build things for architectures that aren't really supported out of the box. I think it might work if you start off with llvm-mingw and build rust on top of that, instead of relying on prebuilt toolchains.

**Comment by Alovchin91** [comment]
AFAIK the toolchain should have an explicit specification in Rust. @alexcrichton would know much more about this 😅

I plan to prepare a rustc build environment on my SPX to run compiler tests on arm64, so I could also try to add an aarch64-windows-gnu toolchain, but as of today there is none.

**Pull request merged**
