### PR TITLE
USE_NSECS fixes

### PR DESCRIPTION
**Pull request by ethomson**
Include some nanosecond handling fixes for Android NDK's `struct stat`, which uses neither `st_mtim` nor `st_mtimespec` to contain a `struct timespec`, and instead simply lays down an `st_mtime_nsec` field next to `st_mtime`.

Move us over to using that by default, and then setting:

    #define st_mtime_nsec mtim.tv_nsec

for compatibility with saner platforms.  This is akin to the backcompat behavior with `st_mtime` and so should seem relatively normal everywhere.

Also, fix a unit test that assumed that it would not be run in a `USE_NSECS=ON` environment:  it validated that when writing a new index entry that the nanoseconds would be truncated and thus `0`.  (It was meant to ensure that we did not propagate *old* nanosecond entries that git.git wrote.  We should, of course, validate that we write *our own* values when we're running with nanoseconds enabled.)

### CODE REVIEW

**Comment by ethomson** [comment]
Fixes #3635

**Comment by ethomson** [comment]
(Note that #3635 failed when `USE_NSECS=ON` or not, because we always assumed there was a `struct timespec` in `struct stat`, even when building without `USE_NSECS=ON`).

**Comment by carlosmn** [comment]
This is beautiful in a train-crash kind of way :+1:

**Comment by ethomson** [comment]
> This is beautiful in a train-crash kind of way 

That's not the first time that's been said about me.

**Pull request merged**
