### PR TITLE
Added call to git_libgit2_shutdown()

### LINKED ISSUE #3076: Looks like git2.c example is missing git_libgit2_shutdown(); call.
It calls git_libgit2_init(), but not shutdown.

### PR DESCRIPTION
**Pull request by volftomas**
Added forgotten call to git_libgit2_shutdown() to the /examples/network/git2.c.

Should fix #3076

### CODE REVIEW

**Comment by ethomson** [comment]
Thank you!

If you wouldn't mind tweaking this a little bit, I think that our recommendation is generally to call `git_libgit2_init` at the start of program execution and call `git_libgit2_shutdown` at the end.  There shouldn't be anything wrong with the pattern in this PR - which calls `init` and `shutdown` repeatedly, but it is less efficient as it would allocate / deallocate data repeatedly.

Since this is an example, we would like to point people towards the most recommended style.

I think that keeping the `init` in its current location, having a `shutdown` at the end of the `main` function would be the most recommended for consumers.  (Looking at the existing logic, of course, we would have to change that a bit so that we no longer return early from `run_command` and make sure to do the cleanup in `main`.)

Do you agree?  If so, would you mind updating this pull request?

Thanks again!

**Comment by volftomas** [comment]
Sounds like a good idea, will update pull request today/tomorrow ^_^

**Comment by volftomas** [comment]
Look it over, should be nicer now.

**Comment by ethomson** [comment]
It is!  This looks great; thanks!

**Pull request merged**
