### PR TITLE
Improve clar messages

### PR DESCRIPTION
**Pull request by ethomson**
Provide more detailed messages when conditions pass or fail unexpectedly.  In particular, this provides the error messages when a test fails with a different error code than was expected.

`cl_git_pass` failures look unchanged:
```
  1) Failure:
apply::fromfile::test_name [tests/apply/fromfile.c:42]
  Function call failed: (git_patch_from_buffer(&patch, "", 0, ((void *)0)))
  error -3 - no patch found
```

`cl_git_fail` messages now:
```
  1) Failure:
apply::fromfile::test_name [tests/apply/fromfile.c:42]
  Function call succeeded: git_patch_from_buffer(&patch, patchfile, strlen(patchfile), NULL)
  no error, expected non-zero return
```

`cl_git_fail_with` messages now:
```
  1) Failure:
apply::fromfile::test_name [tests/apply/fromfile.c:42]
  Function call failed: (git_patch_from_buffer(&patch, "", 0, ((void *)0)))
  error -3 (expected -99) - no patch found
```

/cc @pks-t

### CODE REVIEW

**Comment by ethomson** [comment]
The goal here is to see more information about why some tests fail in appveyor.  We expect certificate failures, but are getting a generic `-1` failure.  Shoddy networking, but it would be interesting to see a bit more details.

**Comment by pks-t** [comment]
Very nice.

You forgot to modfiy all existing callsites of `cl_git_report_failure` ;)

What do you think about using `cl_git_expect` instead of `cl_git_exec` as the macro's name?

**Comment by ethomson** [comment]
I did forget win32!  Oops!

I had this as `cl_git_expect` or something similar to begin with, so I was rather on the fence.  It sounds like you prefer that, so I've changed `cl_git_exec` -> `cl_git_expect`.

**Comment by pks-t** [comment]
`cl_git_exec` did not really sound as if it would check anything but only execute a function. So I think `cl_git_expect` makes the function a bit more obvious in its behavior.

Thanks, looks good to me.

**Pull request merged**
