### PR TITLE
Correction of compilation warnings with GCC 4.8

### PR DESCRIPTION
**Pull request by jozef-matula**
Hi,

I'm using libgit2 with GCC with "-ansi -pedantic" mode enabled. This leads to several compilation warnings which are fixed in these 2 commits.

Hope this could be merged in the baseline.

Jozef

### CODE REVIEW

**Comment by ethomson** [comment]
I'm afraid that we have explicitly decided that a warning-free compilation with `-pedantic` is *not* something that we want to strive for, if it negatively impacts the maintainability of the project. (see the background in issue #2125).

In this case, adding new `enum`s is more burdenful (and has a larger diff area) and we believe is not worth the benefit of being able to compile warning-free with `-pedantic`.  If you're seeing *errors* and not *warnings* (without `-Wall`, obviously) then this would be an area we would like to fix.

**Comment by jozef-matula** [comment]
I'm using your library from a C++ project with ``-pedantic`` enabled and also with ``-Werror``. Whenever I upgrade libgit2, I need to redo all my patches what is a bit annoying. Sure I could implement some C-only wrapper layer to workaround this but I don't find this elegant at all. But it seems that I'm the only person in the world having this issue...

I see your point with larger diff area, but does it happen that often? Anyway there is a little flaw in your code style then - in most cases there is a comma after the last enum item, but sometimes there isn't (case of ``git_cvar_t``, ``git_error_t``, ``git_direction``, ``git_remote_autotag_option_t``, ``git_trace_level_t``; I wouldn't count ``git_submodule_ignore_t``, ``git_checkout_notify_t``).

Wouldn't be at least 2a06976165cd6b5d4d217f479f099112991e9cf4 worth of merging? Sure it is just a warning fix (the only warning in the current GCC build), but it follows the "keep local variable declarations at the tops of blocks only" rule from your Conventions.

**Comment by carlosmn** [comment]
More crucial than `-pedantic` is the `-ansi` flag, which makes GCC care that the code should be C89/C90. We don't care about being absolutely C89 complient. We want to be C99, but can only use the subset of features which is available under MSVC. Otherwise we would be even further away from code accepted by the `-ansi` flag.

**Comment by carlosmn** [comment]
As for that 2a06 commit, it wouldn't hurt, but it doesn't fix an issue with compilation. The only time the `GIT_UNUSED` macro would cause an issue is when we use iconv, which means MacOS X which means we're using clang or gcc and thus have this feature available to us. In the common code we must keep declarations before the code because of MSVC, but in this case it's not involved.

**Comment by ethomson** [comment]
> Wouldn't be at least 2a06976 worth of merging?

Yes, I agree that it would.  Thanks for this.  I merged this commit into master.

**Pull request closed without merging**
