### PR TITLE
Tell user if libssh was not found

### PR DESCRIPTION
**Pull request by urkud**

### CODE REVIEW

**Comment by ethomson** [comment]
This seems friendly.  Thanks!

**Comment by carlosmn** [comment]
By default, the pkg-config helper does not take the CMake prefixes into account, thus doing what this message suggests will not change anything in the search process (see the documentation at the bottom of your `FindPkgConfig.cmake`)

We also already tell the user that we cannot find libssh2. The two lines prior to this message are about searching for and not finding libssh2. If this is about telling what to do for non-standard locations, then it should be just about that, but then it needs to be accurate.

```
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5")
-- checking for module 'libssh2'
--   package 'libssh2' not found
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
-- Found Iconv: -L/usr/lib -liconv
```

**Comment by urkud** [comment]
You're right. Feel free to revert this change.

What do you think about using FeatureSummary? There're 3 options:

1. Increase the required cmake version.
2. Use it only if it's available.
3. Copy it from cmake sources.

**Comment by carlosmn** [comment]
From the name, it sounds useful, though we can probably add a bit of logic at the end if it requires a pretty new CMake version.

**Comment by sprintr** [comment]
What is the standard location of libssh2? I need to integrate it with libssh2 that I built with `CMAKE_INSTALL_PREFIX`=<libssh2_path>. Pointing `CMAKE_PREFIX_PATH` at <libssh2_path> doesn't seem to work.

**Comment by carlosmn** [comment]
There's not standard location *for libssh2*. Your operating system has a few standard paths where `pkg-config` will look for packages, typically `/usr/lib/` and `/usr/local/lib/` but there can be more depending on your OS and how it handles (or handled) 32-bit vs 64-bit vs multi-arch.

If you want CMake to find your libssh2, you need to add the pkgconfig path to the `PKG_CONFIG_PATH` for it to be able to find it. The prefixes don't have to be the same for libssh2 and libgit2, the build system just needs to know where libssh2 lives. You may then also need to adjust the library load paths if libssh2 is outside of the usual paths provided by your operating system. This is however about how your OS handles libraries and loading, rather than something libgit2 or libssh2 do.

**Comment by sprintr** [comment]
Cool! will give this a try.

**Pull request merged**
