### PR TITLE
Configuration file fixes with includes

### PR DESCRIPTION
**Pull request by pks-t**
This fixes the issues causing #4247, but it does not yet fix additional issues with includes. One more issue I found was that upon refreshing a config file, we'll duplicate the includes inside the readers struct, if I'm not mistaken. I'll try to tackle this problem tomorrow, alongside with some tests for the broken behaviour.

### CODE REVIEW

**Comment by pks-t** [comment]
As ever so often, this PR has grown quite a lot again as several other issues have popped up :P So I've started refactoring our configuration includes code to be easier to maintain and fix these bugs. I hope that these refactorings might ease further improvements alongside with include files,for example when modifying variables in the correct config file.

But yeah, I'm done with that code for now, not to keen on revisiting it too soon :slightly_smiling_face:

**Comment by csware** [comment]
Any plans when this gets merged?

**Comment by pks-t** [comment]
While I'd like to get it merged soon-ish, I won't merge without some thorough review as it touches quite some internals of how we handle config files. So doing reviews would definitly accelerate getting this PR ready.

**Comment by ethomson** [comment]
🎉

**Pull request merged**
