### PR TITLE
attr_file: fix subdirectory attr case.

### LINKED ISSUE #2966: Ignore rules prioritize !dir/subdir over earlier specific file rules
Using bdf0e734506b5b18234d48a0e7c6995aeda30b9d.

With this .gitignore file:

```
x
folder/*
!folder/child
```

And these files in the working directory:

```
folder/x
folder/child/x
```

`git` ignores `folder/x` and `folder/child/x`, while libgit2 ignores only `folder/x`.

### PR DESCRIPTION
**Pull request by mikemcquaid**
Fixes #2966 where `.gitignore` files in subdirectories are sometimes not respected.

I'm not totally sure if the fix is the best approach to take but hopefully the first commit (https://github.com/libgit2/libgit2/commit/90286c15adc264d220f4a47633ceb72e5effb2f6) with a failing test should provide a good start to work on this. CC @robrix who filed this issue.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Seems the CI failures are unrelated to the changes. Tests all pass for me locally.

**Comment by robrix** [comment]
@mikemcquaid Does this overlap with https://github.com/libgit2/libgit2/pull/3016 ?

**Comment by mikemcquaid** [comment]
@robrix Honestly I'm not totally sure; my test case is slightly different. I'll take a look and merge that branch on top of this one and see if that fix fixes by case.

**Comment by robrix** [comment]
:+1:

**Comment by mikemcquaid** [comment]
@robrix I've confirmed that #3016 does not fix the test-case here. They seem to be different issues.

**Comment by robrix** [comment]
Thanks @mikemcquaid! :bow:

@libgit2/owners, I’m not comfortable enough with the code base to review this, could someone step in when they have a moment? :heart_decoration:

**Comment by mikemcquaid** [comment]
Fixed the Windows build so this is green. Let me know if there's any changes needed.

**Comment by robrix** [comment]
@libgit2/owners *bump*

**Comment by carlosmn** [comment]
Thanks, I added a line to the test and merged manually.

**Comment by robrix** [comment]
Thank you @mikemcquaid :heart_decoration:!

**Comment by mikemcquaid** [comment]
Woohoo, thanks for the merge!

**Pull request closed without merging**
