### PR TITLE
Performance improvement to eliminate some tolower calls

### PR DESCRIPTION
**Pull request by jeffhostetler**
Eliminate some calls to tolower() duing iteration and path validation during checkout.

tolower() is very expensive on Windows.  I changed 2 sections where a path is being compared against a constant string using tolower().

### CODE REVIEW

**Comment by ethomson** [comment]
Hah.  I think I had this all unrolled like this originally and @vmg spit in my eye.

**Comment by ethomson** [comment]
Seriously though, for people reading this without the background, `tolower` in the Windows C runtime (14.0) *takes a lock(!?)* so that it can determine your locale safely.

That's pointless for us since we're dealing with a literal single byte that represents an ASCII character.

**Comment by jeffhostetler** [comment]
Guess I did kind of bury the lead there, didn't I.  :-) 
Yes, tolower() takes a lock.  And we're calling it in a loop....

There are other places that do this, but I didn't want to change too many places at once.

**Comment by ethomson** [comment]
Couple of random questions - what if we don't compile with `-DUNICODE`?  (This is probably a non-issue - I don't think that we do in the CMake-generated `.sln`s, but I'm curious).

But I think the meat of the problem is that I'm not sure that we've thought carefully about case folding in all cases.  I think we work pretty nicely if your locale is `*.UTF-8` (which, thankfully, you would expect it to be on most non-Windows platforms).

But we're relying on `strcasecmp` to do UTF-8 for us, which simply isn't always true.  (If I set my locale to `C` or `Latin1` on a machine with a case insensitive filesystem, will our test suite pass?  I actually suspect it will not.)

Anyway, I think that we should not rely on this.  We should probably have a UTF-8 aware `strcasecmp`.  I haven't looked deeply, but I suspect we can just make `git__strcasecmp` always work on UTF-8 instead of the current locale.  We have a general rule that strings are always UTF-8 inside the library that I think allows us to make this change relatively safely.  (This may need to be better-documented - by taking `char *` on Windows, this is pretty obvious that we don't speak UCS-2 and a user will be forced to think about this, but that's not necessarily true on Unixy systems, where somebody might not think deeply about the encoding they're passing.)

We already stole some code from utf8proc - I wonder if we can't grab a case folding map from them too to make this easy?

Is this crazy?

**Comment by jeffhostetler** [comment]
There are lots of good questions here and I'm not sure of the answers.

There are several independent issues here:
* do the platform strcasecmp() and tolower() and friends actually do UTF-8 and/or respect locale?

* do we want them to?  (since we sometimes we are playing with a tree/index (in canonical form?) and sometimes we are playing with a WD/filesystem.  and sometimes we are playing with both forms.

* or do we need multiple sets of these routines, to be used in each of these contexts?

* both Windows and Mac are case-insensitve, but are they equally insensitive?  That is, does Windows case-fold UCS-2 chars above 0x80 the same way that Mac does (or vice versa more likely)?

**Comment by ethomson** [comment]
> do the platform strcasecmp() and tolower() and friends actually do UTF-8 and/or respect locale?

They should respect locale.  glibc does, anyway.  I can't speak to Mac, nor more exotic Unixes.

> do we want them to? (since we sometimes we are playing with a tree/index (in canonical form?) and sometimes we are playing with a WD/filesystem. and sometimes we are playing with both forms.

Good question.  We say that we're UTF-8 internally.  The git trees and index are in UTF-8 (by definition).  As for the workdir...  on Windows, anything coming from the workdir iterator is UTF-8 (because we explicitly converted it from UCS-2).  We can speak intelligently about Mac (UTF-8 decomposed) because it's Apple and they're weird, but at least they're consistent.  Everything else, no, I think is a stream of bytes to interpreted by your locale?  (Sheesh).

The good news here, though, is that we really only do `strcasecmp` against workdir paths when `core.ignorecase = true`, which is really only Mac and Windows.  So while strictly speaking you could have a `core.ignorecase = true` on some platform that used an opaque bytestream for filenames that was to be interpreted in the user's locale, in practice, that doesn't really happen for us.

(Let me insert a giant asterisk here, because I'm sure that there is probably one lurking out there somewhere, but let's leave that buggy for now and deal with it later because there is no `strcasecmp` that will let us compare a UTF-8 string against a string in the user's locale when that user's locale is not UTF-8.  So we're no worse off than we are today.)

> or do we need multiple sets of these routines, to be used in each of these contexts?

No, let's avoid this.

> both Windows and Mac are case-insensitve, but are they equally insensitive? That is, does Windows case-fold UCS-2 chars above 0x80 the same way that Mac does (or vice versa more likely)?

I don't know.

**Comment by tkelman** [comment]
> We already stole some code from utf8proc - I wonder if we can't grab a case folding map from them too to make this easy?

BTW JuliaLang is now officially maintaining utf8proc (with the blessing of PSG), it lives at https://github.com/JuliaLang/utf8proc going forward.

Unicode case folding has come up a few times (e.g. https://github.com/JuliaLang/julia/issues/7848 - note that "libmojibake" was our temporary working name for the development fork of utf8proc), AIUI utf8proc is locale-agnostic.

**Comment by ethomson** [comment]
To circle back:  this is more problematic than just this slice of code.  Obviously we do a lot of case insensitive comparisons.

Let's improve `strcasecmp` and `tolower` so that this is a general fix instead of trying to unroll this one specific case.

**Comment by jeffhostetler** [comment]
That's fine.  I'll close this and look at a broader fix when I get a free moment.

**Pull request closed without merging**
