### PR TITLE
Win32: Enable WinHTTP for MinGW

### PR DESCRIPTION
**Pull request by phkelley**
This change enables the use of WinHTTP in the MinGW Win32 build. We were previously not doing this because MinGW does not come with a header file for WinHTTP (`winhttp.h`) or an import library (`libwinhttp.a`).

To work around this, I have grabbed the LGPL copy of winhttp.h from the Wine project, and added logic to the build to generate the import library (`libwinhttp.a`) from a hand-made .def file. This import library generation is done using dlltool, which is a standard part of the MinGW distribution. I also created a minimal `urlmon.h`, needed for us to call `MapUrlToZone` and find out whether to use the user's 'default credentials' when authenticating to a Windows-based Git HTTP server.

This change creates greater alignment between the MSVC and MinGW builds. They now both are able to pass the "online" test suite in their default configuration, without having to set up OpenSSL, etc.

I also modified how our CI build performs the MinGW build on Linux. We now use a custom toolchain file. This has the following advantages:
* Far fewer warnings emitted by the build. The previous iteration was very noisy.
* The CI build creates actual PE binaries (libgit2.dll and libgit2_clar.exe) instead of ELF.
* The build no longer skips the creation of the test suite binary, so we have expanded compile-time coverage on Win32.

### CODE REVIEW

**Comment by carlosmn** [comment]
There's a bunch of different patches in the PR so it works across the mingw systems. Could someone who's using this post a patch to apply on top of this PR? Or create their own PR with both sets of changes?

**Comment by arthurschreiber** [comment]
@carlosmn: On another note, we should be able to run mingw builds on appveyor as well.

**Comment by tkelman** [comment]
Or on Travis - there's already a cross-compile matrix build using `i586-mingw32msvc-gcc`, you could add `i686-w64-mingw32-gcc` and/or `x86_64-w64-mingw32-gcc` to that via this PPA: https://launchpad.net/~tobydox/+archive/ubuntu/mingw-x-precise

**Comment by arthurschreiber** [comment]
@tkelman But we can't run the tests then... We're already cross compiling on travis.

**Comment by tkelman** [comment]
Tests might be runnable via wine. AppVeyor probably would be more useful, just depends whether or not a bigger build matrix and longer CI run times are an issue. I think AppVeyor VM's have 32-bit mingw.org preinstalled, you'd have to download a mingw-w64 distribution to test that - we use one from http://sourceforge.net/projects/mingw-w64-dgn/files/mingw-w64 for Julia's builds, and put it in the AppVeyor `cache:` so it doesn't have to be downloaded from sourceforge on every build.

**Comment by ethomson** [comment]
We pay cash money for AppVeyor, so it's much faster than Travis.  Plus cross compiling is a challenge.  But WINE would be very unfortunate indeed.

**Comment by tkelman** [comment]
I'm not using this patch so unsure on this material, but I can try a PR for putting mingw into the appveyor matrix. They have legacy mingw.org installed on the worker VMs by default, but for mingw-w64 you'd have to pick a distribution to download (and probably cache, too). Anywhere from 1 to 3 new matrix entries might make sense out of the following.

1. 32 bit mingw.org
2. 32 bit mingw-w64
3. 64 bit mingw-w64

**Comment by ethomson** [comment]
@tkelman If you would put together a PR for this, that would be *amazing*.  :sparkles:

**Comment by tkelman** [comment]
> There's a bunch of different patches in the PR so it works across the mingw systems. Could someone who's using this post a patch to apply on top of this PR? Or create their own PR with both sets of changes?

See #2986 - everyone here whose patches I've adapted, please check that I didn't mess something up.

**Comment by carlosmn** [comment]
Merged via #2986

**Pull request closed without merging**
