### PR TITLE
README: provide some more explanation about TLS

### PR DESCRIPTION
**Pull request by ethomson**

### CODE REVIEW

**Comment by ethomson** [comment]
Per #2915

**Comment by scunz** [comment]
What should one do if neither is possible? i.e. the worker threads are managed by a framework, so it's not possible to run something when they exit, neither can a identifier for them be accessed so that it would be possible to join them before termination?

**Comment by ethomson** [comment]
You don't need to call it *at thread exit*.  You just need to `git_libgit2_init`, then do some work, then `git_libgit2_shutdown`, no?

**Comment by scunz** [comment]
Yes, you're right of course. I meanwhile looked up the code for this and the whole context in which this README change is. It's perfectly fine to just surround any background work whatsoever with a `_init` and `_shutdown` call.

**Comment by ethomson** [comment]
:sparkles: Thanks @scunz - I don't often use the pthreads `init` / `shutdown`, so I'm always happy to have a second set of eyes.

**Comment by scunz** [comment]
@ethomson It's the same for all platforms: these two functions essentially turn the whole of the library into a resource. When I wrote "surround any background work whatsoever", I was actually thinking about something along the line of the [using statement](https://msdn.microsoft.com/en-us/library/yh598w02.aspx) in C#.

**Pull request merged**
