### PR TITLE
tests: Add create__symbolic_with_arbitrary_content

### PR DESCRIPTION
**Pull request by richardipsum**
This test ensures that it's possible to create a symbolic ref that
has arbitrary data as its target. It also ensures it's possible
to obtain the target of that symbolic reference from the git_reference
object.

### CODE REVIEW

**Comment by ethomson** [comment]
The AppVeyor mingw builds are busted at the moment.  I'm looking into it; please ignore build failures from those hosts for now.

**Comment by richardipsum** [comment]
I noticed some whitespace/style issues while I was doing that so I fixed them up and tacked them on as an extra commit.

For what it's worth while rerunning the test suite locally, just to be sure, I notice that the clar tests fail if run via the Makefile but not when run directly, this happens on master as well so I'm pretty sure it's unrelated to my changes.

I have some free time today so I might check out why that's happening.

**Comment by richardipsum** [comment]
I think the tests are failing due to networking issues at my end, so nothing to worry about. I needed to do some googling to figure out how to get the tests to print the exact failure to the screen without manually modifying the generated Makefile. I've submitted https://github.com/libgit2/libgit2/pull/4139 to add a note to the README on how to do this.

**Comment by ethomson** [comment]
Cool, thanks!  😀

**Pull request merged**
